<?php

/**
 * Base static class for performing query and update operations on the 'factura' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Wed Nov 25 23:58:30 2009
 *
 * @package    lib.model.profit.om
 */
abstract class BaseFacturaPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'profit';

	/** the table name for this class */
	const TABLE_NAME = 'factura';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.profit.Factura';

	/** The total number of columns. */
	const NUM_COLUMNS = 41;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the FACT_NUM field */
	const FACT_NUM = 'factura.FACT_NUM';

	/** the column name for the CONTRIB field */
	const CONTRIB = 'factura.CONTRIB';

	/** the column name for the NOMBRE field */
	const NOMBRE = 'factura.NOMBRE';

	/** the column name for the RIF field */
	const RIF = 'factura.RIF';

	/** the column name for the NIT field */
	const NIT = 'factura.NIT';

	/** the column name for the NUM_CONTROL field */
	const NUM_CONTROL = 'factura.NUM_CONTROL';

	/** the column name for the STATUS field */
	const STATUS = 'factura.STATUS';

	/** the column name for the COMENTARIO field */
	const COMENTARIO = 'factura.COMENTARIO';

	/** the column name for the DESCRIP field */
	const DESCRIP = 'factura.DESCRIP';

	/** the column name for the SALDO field */
	const SALDO = 'factura.SALDO';

	/** the column name for the FEC_EMIS field */
	const FEC_EMIS = 'factura.FEC_EMIS';

	/** the column name for the FEC_VENC field */
	const FEC_VENC = 'factura.FEC_VENC';

	/** the column name for the CO_CLI field */
	const CO_CLI = 'factura.CO_CLI';

	/** the column name for the CO_VEN field */
	const CO_VEN = 'factura.CO_VEN';

	/** the column name for the CO_TRAN field */
	const CO_TRAN = 'factura.CO_TRAN';

	/** the column name for the DIR_ENT field */
	const DIR_ENT = 'factura.DIR_ENT';

	/** the column name for the FORMA_PAG field */
	const FORMA_PAG = 'factura.FORMA_PAG';

	/** the column name for the TOT_BRUTO field */
	const TOT_BRUTO = 'factura.TOT_BRUTO';

	/** the column name for the TOT_NETO field */
	const TOT_NETO = 'factura.TOT_NETO';

	/** the column name for the GLOB_DESC field */
	const GLOB_DESC = 'factura.GLOB_DESC';

	/** the column name for the TOT_RECA field */
	const TOT_RECA = 'factura.TOT_RECA';

	/** the column name for the PORC_GDESC field */
	const PORC_GDESC = 'factura.PORC_GDESC';

	/** the column name for the PORC_RECA field */
	const PORC_RECA = 'factura.PORC_RECA';

	/** the column name for the TOTAL_UC field */
	const TOTAL_UC = 'factura.TOTAL_UC';

	/** the column name for the TOTAL_CP field */
	const TOTAL_CP = 'factura.TOTAL_CP';

	/** the column name for the TOT_FLETE field */
	const TOT_FLETE = 'factura.TOT_FLETE';

	/** the column name for the MONTO_DEV field */
	const MONTO_DEV = 'factura.MONTO_DEV';

	/** the column name for the TOTKLU field */
	const TOTKLU = 'factura.TOTKLU';

	/** the column name for the ANULADA field */
	const ANULADA = 'factura.ANULADA';

	/** the column name for the IMPRESA field */
	const IMPRESA = 'factura.IMPRESA';

	/** the column name for the IVA field */
	const IVA = 'factura.IVA';

	/** the column name for the IVA_DEV field */
	const IVA_DEV = 'factura.IVA_DEV';

	/** the column name for the NUMCOM field */
	const NUMCOM = 'factura.NUMCOM';

	/** the column name for the TASA field */
	const TASA = 'factura.TASA';

	/** the column name for the DIS_CEN field */
	const DIS_CEN = 'factura.DIS_CEN';

	/** the column name for the VUELTO field */
	const VUELTO = 'factura.VUELTO';

	/** the column name for the SERIALES field */
	const SERIALES = 'factura.SERIALES';

	/** the column name for the TASAG field */
	const TASAG = 'factura.TASAG';

	/** the column name for the TASAG10 field */
	const TASAG10 = 'factura.TASAG10';

	/** the column name for the TASAG20 field */
	const TASAG20 = 'factura.TASAG20';

	/** the column name for the ID field */
	const ID = 'factura.ID';

	/**
	 * An identiy map to hold any loaded instances of Factura objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Factura[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('FactNum', 'Contrib', 'Nombre', 'Rif', 'Nit', 'NumControl', 'Status', 'Comentario', 'Descrip', 'Saldo', 'FecEmis', 'FecVenc', 'CoCli', 'CoVen', 'CoTran', 'DirEnt', 'FormaPag', 'TotBruto', 'TotNeto', 'GlobDesc', 'TotReca', 'PorcGdesc', 'PorcReca', 'TotalUc', 'TotalCp', 'TotFlete', 'MontoDev', 'Totklu', 'Anulada', 'Impresa', 'Iva', 'IvaDev', 'Numcom', 'Tasa', 'DisCen', 'Vuelto', 'Seriales', 'Tasag', 'Tasag10', 'Tasag20', 'Id', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('factNum', 'contrib', 'nombre', 'rif', 'nit', 'numControl', 'status', 'comentario', 'descrip', 'saldo', 'fecEmis', 'fecVenc', 'coCli', 'coVen', 'coTran', 'dirEnt', 'formaPag', 'totBruto', 'totNeto', 'globDesc', 'totReca', 'porcGdesc', 'porcReca', 'totalUc', 'totalCp', 'totFlete', 'montoDev', 'totklu', 'anulada', 'impresa', 'iva', 'ivaDev', 'numcom', 'tasa', 'disCen', 'vuelto', 'seriales', 'tasag', 'tasag10', 'tasag20', 'id', ),
		BasePeer::TYPE_COLNAME => array (self::FACT_NUM, self::CONTRIB, self::NOMBRE, self::RIF, self::NIT, self::NUM_CONTROL, self::STATUS, self::COMENTARIO, self::DESCRIP, self::SALDO, self::FEC_EMIS, self::FEC_VENC, self::CO_CLI, self::CO_VEN, self::CO_TRAN, self::DIR_ENT, self::FORMA_PAG, self::TOT_BRUTO, self::TOT_NETO, self::GLOB_DESC, self::TOT_RECA, self::PORC_GDESC, self::PORC_RECA, self::TOTAL_UC, self::TOTAL_CP, self::TOT_FLETE, self::MONTO_DEV, self::TOTKLU, self::ANULADA, self::IMPRESA, self::IVA, self::IVA_DEV, self::NUMCOM, self::TASA, self::DIS_CEN, self::VUELTO, self::SERIALES, self::TASAG, self::TASAG10, self::TASAG20, self::ID, ),
		BasePeer::TYPE_FIELDNAME => array ('fact_num', 'contrib', 'nombre', 'rif', 'nit', 'num_control', 'status', 'comentario', 'descrip', 'saldo', 'fec_emis', 'fec_venc', 'co_cli', 'co_ven', 'co_tran', 'dir_ent', 'forma_pag', 'tot_bruto', 'tot_neto', 'glob_desc', 'tot_reca', 'porc_gdesc', 'porc_reca', 'total_uc', 'total_cp', 'tot_flete', 'monto_dev', 'totklu', 'anulada', 'impresa', 'iva', 'iva_dev', 'numcom', 'tasa', 'dis_cen', 'vuelto', 'seriales', 'tasag', 'tasag10', 'tasag20', 'ID', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('FactNum' => 0, 'Contrib' => 1, 'Nombre' => 2, 'Rif' => 3, 'Nit' => 4, 'NumControl' => 5, 'Status' => 6, 'Comentario' => 7, 'Descrip' => 8, 'Saldo' => 9, 'FecEmis' => 10, 'FecVenc' => 11, 'CoCli' => 12, 'CoVen' => 13, 'CoTran' => 14, 'DirEnt' => 15, 'FormaPag' => 16, 'TotBruto' => 17, 'TotNeto' => 18, 'GlobDesc' => 19, 'TotReca' => 20, 'PorcGdesc' => 21, 'PorcReca' => 22, 'TotalUc' => 23, 'TotalCp' => 24, 'TotFlete' => 25, 'MontoDev' => 26, 'Totklu' => 27, 'Anulada' => 28, 'Impresa' => 29, 'Iva' => 30, 'IvaDev' => 31, 'Numcom' => 32, 'Tasa' => 33, 'DisCen' => 34, 'Vuelto' => 35, 'Seriales' => 36, 'Tasag' => 37, 'Tasag10' => 38, 'Tasag20' => 39, 'Id' => 40, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('factNum' => 0, 'contrib' => 1, 'nombre' => 2, 'rif' => 3, 'nit' => 4, 'numControl' => 5, 'status' => 6, 'comentario' => 7, 'descrip' => 8, 'saldo' => 9, 'fecEmis' => 10, 'fecVenc' => 11, 'coCli' => 12, 'coVen' => 13, 'coTran' => 14, 'dirEnt' => 15, 'formaPag' => 16, 'totBruto' => 17, 'totNeto' => 18, 'globDesc' => 19, 'totReca' => 20, 'porcGdesc' => 21, 'porcReca' => 22, 'totalUc' => 23, 'totalCp' => 24, 'totFlete' => 25, 'montoDev' => 26, 'totklu' => 27, 'anulada' => 28, 'impresa' => 29, 'iva' => 30, 'ivaDev' => 31, 'numcom' => 32, 'tasa' => 33, 'disCen' => 34, 'vuelto' => 35, 'seriales' => 36, 'tasag' => 37, 'tasag10' => 38, 'tasag20' => 39, 'id' => 40, ),
		BasePeer::TYPE_COLNAME => array (self::FACT_NUM => 0, self::CONTRIB => 1, self::NOMBRE => 2, self::RIF => 3, self::NIT => 4, self::NUM_CONTROL => 5, self::STATUS => 6, self::COMENTARIO => 7, self::DESCRIP => 8, self::SALDO => 9, self::FEC_EMIS => 10, self::FEC_VENC => 11, self::CO_CLI => 12, self::CO_VEN => 13, self::CO_TRAN => 14, self::DIR_ENT => 15, self::FORMA_PAG => 16, self::TOT_BRUTO => 17, self::TOT_NETO => 18, self::GLOB_DESC => 19, self::TOT_RECA => 20, self::PORC_GDESC => 21, self::PORC_RECA => 22, self::TOTAL_UC => 23, self::TOTAL_CP => 24, self::TOT_FLETE => 25, self::MONTO_DEV => 26, self::TOTKLU => 27, self::ANULADA => 28, self::IMPRESA => 29, self::IVA => 30, self::IVA_DEV => 31, self::NUMCOM => 32, self::TASA => 33, self::DIS_CEN => 34, self::VUELTO => 35, self::SERIALES => 36, self::TASAG => 37, self::TASAG10 => 38, self::TASAG20 => 39, self::ID => 40, ),
		BasePeer::TYPE_FIELDNAME => array ('fact_num' => 0, 'contrib' => 1, 'nombre' => 2, 'rif' => 3, 'nit' => 4, 'num_control' => 5, 'status' => 6, 'comentario' => 7, 'descrip' => 8, 'saldo' => 9, 'fec_emis' => 10, 'fec_venc' => 11, 'co_cli' => 12, 'co_ven' => 13, 'co_tran' => 14, 'dir_ent' => 15, 'forma_pag' => 16, 'tot_bruto' => 17, 'tot_neto' => 18, 'glob_desc' => 19, 'tot_reca' => 20, 'porc_gdesc' => 21, 'porc_reca' => 22, 'total_uc' => 23, 'total_cp' => 24, 'tot_flete' => 25, 'monto_dev' => 26, 'totklu' => 27, 'anulada' => 28, 'impresa' => 29, 'iva' => 30, 'iva_dev' => 31, 'numcom' => 32, 'tasa' => 33, 'dis_cen' => 34, 'vuelto' => 35, 'seriales' => 36, 'tasag' => 37, 'tasag10' => 38, 'tasag20' => 39, 'ID' => 40, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new FacturaMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. FacturaPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(FacturaPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(FacturaPeer::FACT_NUM);

		$criteria->addSelectColumn(FacturaPeer::CONTRIB);

		$criteria->addSelectColumn(FacturaPeer::NOMBRE);

		$criteria->addSelectColumn(FacturaPeer::RIF);

		$criteria->addSelectColumn(FacturaPeer::NIT);

		$criteria->addSelectColumn(FacturaPeer::NUM_CONTROL);

		$criteria->addSelectColumn(FacturaPeer::STATUS);

		$criteria->addSelectColumn(FacturaPeer::COMENTARIO);

		$criteria->addSelectColumn(FacturaPeer::DESCRIP);

		$criteria->addSelectColumn(FacturaPeer::SALDO);

		$criteria->addSelectColumn(FacturaPeer::FEC_EMIS);

		$criteria->addSelectColumn(FacturaPeer::FEC_VENC);

		$criteria->addSelectColumn(FacturaPeer::CO_CLI);

		$criteria->addSelectColumn(FacturaPeer::CO_VEN);

		$criteria->addSelectColumn(FacturaPeer::CO_TRAN);

		$criteria->addSelectColumn(FacturaPeer::DIR_ENT);

		$criteria->addSelectColumn(FacturaPeer::FORMA_PAG);

		$criteria->addSelectColumn(FacturaPeer::TOT_BRUTO);

		$criteria->addSelectColumn(FacturaPeer::TOT_NETO);

		$criteria->addSelectColumn(FacturaPeer::GLOB_DESC);

		$criteria->addSelectColumn(FacturaPeer::TOT_RECA);

		$criteria->addSelectColumn(FacturaPeer::PORC_GDESC);

		$criteria->addSelectColumn(FacturaPeer::PORC_RECA);

		$criteria->addSelectColumn(FacturaPeer::TOTAL_UC);

		$criteria->addSelectColumn(FacturaPeer::TOTAL_CP);

		$criteria->addSelectColumn(FacturaPeer::TOT_FLETE);

		$criteria->addSelectColumn(FacturaPeer::MONTO_DEV);

		$criteria->addSelectColumn(FacturaPeer::TOTKLU);

		$criteria->addSelectColumn(FacturaPeer::ANULADA);

		$criteria->addSelectColumn(FacturaPeer::IMPRESA);

		$criteria->addSelectColumn(FacturaPeer::IVA);

		$criteria->addSelectColumn(FacturaPeer::IVA_DEV);

		$criteria->addSelectColumn(FacturaPeer::NUMCOM);

		$criteria->addSelectColumn(FacturaPeer::TASA);

		$criteria->addSelectColumn(FacturaPeer::DIS_CEN);

		$criteria->addSelectColumn(FacturaPeer::VUELTO);

		$criteria->addSelectColumn(FacturaPeer::SERIALES);

		$criteria->addSelectColumn(FacturaPeer::TASAG);

		$criteria->addSelectColumn(FacturaPeer::TASAG10);

		$criteria->addSelectColumn(FacturaPeer::TASAG20);

		$criteria->addSelectColumn(FacturaPeer::ID);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(FacturaPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			FacturaPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(FacturaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseFacturaPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseFacturaPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Factura
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = FacturaPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return FacturaPeer::populateObjects(FacturaPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseFacturaPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseFacturaPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(FacturaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			FacturaPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Factura $value A Factura object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Factura $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getFactNum();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Factura object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Factura) {
				$key = (string) $value->getFactNum();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Factura object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Factura Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = FacturaPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = FacturaPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = FacturaPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				FacturaPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

	/**
	 * Returns the number of rows matching criteria, joining the related Clientes table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinClientes(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(FacturaPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			FacturaPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(FacturaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(FacturaPeer::CO_CLI,), array(ClientesPeer::CO_CLI,), $join_behavior);


    foreach (sfMixer::getCallables('BaseFacturaPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseFacturaPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Vendedor table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinVendedor(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(FacturaPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			FacturaPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(FacturaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(FacturaPeer::CO_VEN,), array(VendedorPeer::CO_VEN,), $join_behavior);


    foreach (sfMixer::getCallables('BaseFacturaPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseFacturaPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Transpor table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinTranspor(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(FacturaPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			FacturaPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(FacturaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(FacturaPeer::CO_TRAN,), array(TransporPeer::CO_TRAN,), $join_behavior);


    foreach (sfMixer::getCallables('BaseFacturaPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseFacturaPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Condicio table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinCondicio(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(FacturaPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			FacturaPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(FacturaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(FacturaPeer::FORMA_PAG,), array(CondicioPeer::CO_COND,), $join_behavior);


    foreach (sfMixer::getCallables('BaseFacturaPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseFacturaPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Factura objects pre-filled with their Clientes objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Factura objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinClientes(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseFacturaPeer:doSelectJoin:doSelectJoin') as $callable)
    {
      call_user_func($callable, 'BaseFacturaPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		FacturaPeer::addSelectColumns($c);
		$startcol = (FacturaPeer::NUM_COLUMNS - FacturaPeer::NUM_LAZY_LOAD_COLUMNS);
		ClientesPeer::addSelectColumns($c);

		$c->addJoin(array(FacturaPeer::CO_CLI,), array(ClientesPeer::CO_CLI,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = FacturaPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = FacturaPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = FacturaPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				FacturaPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = ClientesPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = ClientesPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = ClientesPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					ClientesPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Factura) to $obj2 (Clientes)
				$obj2->addFactura($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Factura objects pre-filled with their Vendedor objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Factura objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinVendedor(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		FacturaPeer::addSelectColumns($c);
		$startcol = (FacturaPeer::NUM_COLUMNS - FacturaPeer::NUM_LAZY_LOAD_COLUMNS);
		VendedorPeer::addSelectColumns($c);

		$c->addJoin(array(FacturaPeer::CO_VEN,), array(VendedorPeer::CO_VEN,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = FacturaPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = FacturaPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = FacturaPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				FacturaPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = VendedorPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = VendedorPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = VendedorPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					VendedorPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Factura) to $obj2 (Vendedor)
				$obj2->addFactura($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Factura objects pre-filled with their Transpor objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Factura objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinTranspor(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		FacturaPeer::addSelectColumns($c);
		$startcol = (FacturaPeer::NUM_COLUMNS - FacturaPeer::NUM_LAZY_LOAD_COLUMNS);
		TransporPeer::addSelectColumns($c);

		$c->addJoin(array(FacturaPeer::CO_TRAN,), array(TransporPeer::CO_TRAN,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = FacturaPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = FacturaPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = FacturaPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				FacturaPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = TransporPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = TransporPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = TransporPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					TransporPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Factura) to $obj2 (Transpor)
				$obj2->addFactura($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Factura objects pre-filled with their Condicio objects.
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Factura objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinCondicio(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		FacturaPeer::addSelectColumns($c);
		$startcol = (FacturaPeer::NUM_COLUMNS - FacturaPeer::NUM_LAZY_LOAD_COLUMNS);
		CondicioPeer::addSelectColumns($c);

		$c->addJoin(array(FacturaPeer::FORMA_PAG,), array(CondicioPeer::CO_COND,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = FacturaPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = FacturaPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {

				$omClass = FacturaPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				FacturaPeer::addInstanceToPool($obj1, $key1);
			} // if $obj1 already loaded

			$key2 = CondicioPeer::getPrimaryKeyHashFromRow($row, $startcol);
			if ($key2 !== null) {
				$obj2 = CondicioPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = CondicioPeer::getOMClass();

					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol);
					CondicioPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 already loaded

				// Add the $obj1 (Factura) to $obj2 (Condicio)
				$obj2->addFactura($obj1);

			} // if joined row was not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining all related tables
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAll(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(FacturaPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			FacturaPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(FacturaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria->addJoin(array(FacturaPeer::CO_CLI,), array(ClientesPeer::CO_CLI,), $join_behavior);
		$criteria->addJoin(array(FacturaPeer::CO_VEN,), array(VendedorPeer::CO_VEN,), $join_behavior);
		$criteria->addJoin(array(FacturaPeer::CO_TRAN,), array(TransporPeer::CO_TRAN,), $join_behavior);
		$criteria->addJoin(array(FacturaPeer::FORMA_PAG,), array(CondicioPeer::CO_COND,), $join_behavior);

    foreach (sfMixer::getCallables('BaseFacturaPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseFacturaPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}

	/**
	 * Selects a collection of Factura objects pre-filled with all related objects.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Factura objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAll(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseFacturaPeer:doSelectJoinAll:doSelectJoinAll') as $callable)
    {
      call_user_func($callable, 'BaseFacturaPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		FacturaPeer::addSelectColumns($c);
		$startcol2 = (FacturaPeer::NUM_COLUMNS - FacturaPeer::NUM_LAZY_LOAD_COLUMNS);

		ClientesPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (ClientesPeer::NUM_COLUMNS - ClientesPeer::NUM_LAZY_LOAD_COLUMNS);

		VendedorPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (VendedorPeer::NUM_COLUMNS - VendedorPeer::NUM_LAZY_LOAD_COLUMNS);

		TransporPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (TransporPeer::NUM_COLUMNS - TransporPeer::NUM_LAZY_LOAD_COLUMNS);

		CondicioPeer::addSelectColumns($c);
		$startcol6 = $startcol5 + (CondicioPeer::NUM_COLUMNS - CondicioPeer::NUM_LAZY_LOAD_COLUMNS);

		$c->addJoin(array(FacturaPeer::CO_CLI,), array(ClientesPeer::CO_CLI,), $join_behavior);
		$c->addJoin(array(FacturaPeer::CO_VEN,), array(VendedorPeer::CO_VEN,), $join_behavior);
		$c->addJoin(array(FacturaPeer::CO_TRAN,), array(TransporPeer::CO_TRAN,), $join_behavior);
		$c->addJoin(array(FacturaPeer::FORMA_PAG,), array(CondicioPeer::CO_COND,), $join_behavior);
		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = FacturaPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = FacturaPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = FacturaPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				FacturaPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

			// Add objects for joined Clientes rows

			$key2 = ClientesPeer::getPrimaryKeyHashFromRow($row, $startcol2);
			if ($key2 !== null) {
				$obj2 = ClientesPeer::getInstanceFromPool($key2);
				if (!$obj2) {

					$omClass = ClientesPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					ClientesPeer::addInstanceToPool($obj2, $key2);
				} // if obj2 loaded

				// Add the $obj1 (Factura) to the collection in $obj2 (Clientes)
				$obj2->addFactura($obj1);
			} // if joined row not null

			// Add objects for joined Vendedor rows

			$key3 = VendedorPeer::getPrimaryKeyHashFromRow($row, $startcol3);
			if ($key3 !== null) {
				$obj3 = VendedorPeer::getInstanceFromPool($key3);
				if (!$obj3) {

					$omClass = VendedorPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					VendedorPeer::addInstanceToPool($obj3, $key3);
				} // if obj3 loaded

				// Add the $obj1 (Factura) to the collection in $obj3 (Vendedor)
				$obj3->addFactura($obj1);
			} // if joined row not null

			// Add objects for joined Transpor rows

			$key4 = TransporPeer::getPrimaryKeyHashFromRow($row, $startcol4);
			if ($key4 !== null) {
				$obj4 = TransporPeer::getInstanceFromPool($key4);
				if (!$obj4) {

					$omClass = TransporPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					TransporPeer::addInstanceToPool($obj4, $key4);
				} // if obj4 loaded

				// Add the $obj1 (Factura) to the collection in $obj4 (Transpor)
				$obj4->addFactura($obj1);
			} // if joined row not null

			// Add objects for joined Condicio rows

			$key5 = CondicioPeer::getPrimaryKeyHashFromRow($row, $startcol5);
			if ($key5 !== null) {
				$obj5 = CondicioPeer::getInstanceFromPool($key5);
				if (!$obj5) {

					$omClass = CondicioPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj5 = new $cls();
					$obj5->hydrate($row, $startcol5);
					CondicioPeer::addInstanceToPool($obj5, $key5);
				} // if obj5 loaded

				// Add the $obj1 (Factura) to the collection in $obj5 (Condicio)
				$obj5->addFactura($obj1);
			} // if joined row not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Clientes table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptClientes(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			FacturaPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(FacturaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(FacturaPeer::CO_VEN,), array(VendedorPeer::CO_VEN,), $join_behavior);
				$criteria->addJoin(array(FacturaPeer::CO_TRAN,), array(TransporPeer::CO_TRAN,), $join_behavior);
				$criteria->addJoin(array(FacturaPeer::FORMA_PAG,), array(CondicioPeer::CO_COND,), $join_behavior);

    foreach (sfMixer::getCallables('BaseFacturaPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseFacturaPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Vendedor table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptVendedor(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			FacturaPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(FacturaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(FacturaPeer::CO_CLI,), array(ClientesPeer::CO_CLI,), $join_behavior);
				$criteria->addJoin(array(FacturaPeer::CO_TRAN,), array(TransporPeer::CO_TRAN,), $join_behavior);
				$criteria->addJoin(array(FacturaPeer::FORMA_PAG,), array(CondicioPeer::CO_COND,), $join_behavior);

    foreach (sfMixer::getCallables('BaseFacturaPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseFacturaPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Transpor table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptTranspor(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			FacturaPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(FacturaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(FacturaPeer::CO_CLI,), array(ClientesPeer::CO_CLI,), $join_behavior);
				$criteria->addJoin(array(FacturaPeer::CO_VEN,), array(VendedorPeer::CO_VEN,), $join_behavior);
				$criteria->addJoin(array(FacturaPeer::FORMA_PAG,), array(CondicioPeer::CO_COND,), $join_behavior);

    foreach (sfMixer::getCallables('BaseFacturaPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseFacturaPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Returns the number of rows matching criteria, joining the related Condicio table
	 *
	 * @param      Criteria $c
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     int Number of matching rows.
	 */
	public static function doCountJoinAllExceptCondicio(Criteria $criteria, $distinct = false, PropelPDO $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		// we're going to modify criteria, so copy it first
		$criteria = clone $criteria;

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			FacturaPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		if ($con === null) {
			$con = Propel::getConnection(FacturaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}
	
				$criteria->addJoin(array(FacturaPeer::CO_CLI,), array(ClientesPeer::CO_CLI,), $join_behavior);
				$criteria->addJoin(array(FacturaPeer::CO_VEN,), array(VendedorPeer::CO_VEN,), $join_behavior);
				$criteria->addJoin(array(FacturaPeer::CO_TRAN,), array(TransporPeer::CO_TRAN,), $join_behavior);

    foreach (sfMixer::getCallables('BaseFacturaPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseFacturaPeer', $criteria, $con);
    }


		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}


	/**
	 * Selects a collection of Factura objects pre-filled with all related objects except Clientes.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Factura objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptClientes(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{

    foreach (sfMixer::getCallables('BaseFacturaPeer:doSelectJoinAllExcept:doSelectJoinAllExcept') as $callable)
    {
      call_user_func($callable, 'BaseFacturaPeer', $c, $con);
    }


		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		FacturaPeer::addSelectColumns($c);
		$startcol2 = (FacturaPeer::NUM_COLUMNS - FacturaPeer::NUM_LAZY_LOAD_COLUMNS);

		VendedorPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (VendedorPeer::NUM_COLUMNS - VendedorPeer::NUM_LAZY_LOAD_COLUMNS);

		TransporPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (TransporPeer::NUM_COLUMNS - TransporPeer::NUM_LAZY_LOAD_COLUMNS);

		CondicioPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (CondicioPeer::NUM_COLUMNS - CondicioPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(FacturaPeer::CO_VEN,), array(VendedorPeer::CO_VEN,), $join_behavior);
				$c->addJoin(array(FacturaPeer::CO_TRAN,), array(TransporPeer::CO_TRAN,), $join_behavior);
				$c->addJoin(array(FacturaPeer::FORMA_PAG,), array(CondicioPeer::CO_COND,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = FacturaPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = FacturaPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = FacturaPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				FacturaPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Vendedor rows

				$key2 = VendedorPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = VendedorPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = VendedorPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					VendedorPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Factura) to the collection in $obj2 (Vendedor)
				$obj2->addFactura($obj1);

			} // if joined row is not null

				// Add objects for joined Transpor rows

				$key3 = TransporPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = TransporPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = TransporPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					TransporPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Factura) to the collection in $obj3 (Transpor)
				$obj3->addFactura($obj1);

			} // if joined row is not null

				// Add objects for joined Condicio rows

				$key4 = CondicioPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = CondicioPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = CondicioPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					CondicioPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Factura) to the collection in $obj4 (Condicio)
				$obj4->addFactura($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Factura objects pre-filled with all related objects except Vendedor.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Factura objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptVendedor(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		FacturaPeer::addSelectColumns($c);
		$startcol2 = (FacturaPeer::NUM_COLUMNS - FacturaPeer::NUM_LAZY_LOAD_COLUMNS);

		ClientesPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (ClientesPeer::NUM_COLUMNS - ClientesPeer::NUM_LAZY_LOAD_COLUMNS);

		TransporPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (TransporPeer::NUM_COLUMNS - TransporPeer::NUM_LAZY_LOAD_COLUMNS);

		CondicioPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (CondicioPeer::NUM_COLUMNS - CondicioPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(FacturaPeer::CO_CLI,), array(ClientesPeer::CO_CLI,), $join_behavior);
				$c->addJoin(array(FacturaPeer::CO_TRAN,), array(TransporPeer::CO_TRAN,), $join_behavior);
				$c->addJoin(array(FacturaPeer::FORMA_PAG,), array(CondicioPeer::CO_COND,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = FacturaPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = FacturaPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = FacturaPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				FacturaPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Clientes rows

				$key2 = ClientesPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = ClientesPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = ClientesPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					ClientesPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Factura) to the collection in $obj2 (Clientes)
				$obj2->addFactura($obj1);

			} // if joined row is not null

				// Add objects for joined Transpor rows

				$key3 = TransporPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = TransporPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = TransporPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					TransporPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Factura) to the collection in $obj3 (Transpor)
				$obj3->addFactura($obj1);

			} // if joined row is not null

				// Add objects for joined Condicio rows

				$key4 = CondicioPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = CondicioPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = CondicioPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					CondicioPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Factura) to the collection in $obj4 (Condicio)
				$obj4->addFactura($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Factura objects pre-filled with all related objects except Transpor.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Factura objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptTranspor(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		FacturaPeer::addSelectColumns($c);
		$startcol2 = (FacturaPeer::NUM_COLUMNS - FacturaPeer::NUM_LAZY_LOAD_COLUMNS);

		ClientesPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (ClientesPeer::NUM_COLUMNS - ClientesPeer::NUM_LAZY_LOAD_COLUMNS);

		VendedorPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (VendedorPeer::NUM_COLUMNS - VendedorPeer::NUM_LAZY_LOAD_COLUMNS);

		CondicioPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (CondicioPeer::NUM_COLUMNS - CondicioPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(FacturaPeer::CO_CLI,), array(ClientesPeer::CO_CLI,), $join_behavior);
				$c->addJoin(array(FacturaPeer::CO_VEN,), array(VendedorPeer::CO_VEN,), $join_behavior);
				$c->addJoin(array(FacturaPeer::FORMA_PAG,), array(CondicioPeer::CO_COND,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = FacturaPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = FacturaPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = FacturaPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				FacturaPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Clientes rows

				$key2 = ClientesPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = ClientesPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = ClientesPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					ClientesPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Factura) to the collection in $obj2 (Clientes)
				$obj2->addFactura($obj1);

			} // if joined row is not null

				// Add objects for joined Vendedor rows

				$key3 = VendedorPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = VendedorPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = VendedorPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					VendedorPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Factura) to the collection in $obj3 (Vendedor)
				$obj3->addFactura($obj1);

			} // if joined row is not null

				// Add objects for joined Condicio rows

				$key4 = CondicioPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = CondicioPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = CondicioPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					CondicioPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Factura) to the collection in $obj4 (Condicio)
				$obj4->addFactura($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


	/**
	 * Selects a collection of Factura objects pre-filled with all related objects except Condicio.
	 *
	 * @param      Criteria  $c
	 * @param      PropelPDO $con
	 * @param      String    $join_behavior the type of joins to use, defaults to Criteria::LEFT_JOIN
	 * @return     array Array of Factura objects.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectJoinAllExceptCondicio(Criteria $c, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		$c = clone $c;

		// Set the correct dbName if it has not been overridden
		// $c->getDbName() will return the same object if not set to another value
		// so == check is okay and faster
		if ($c->getDbName() == Propel::getDefaultDB()) {
			$c->setDbName(self::DATABASE_NAME);
		}

		FacturaPeer::addSelectColumns($c);
		$startcol2 = (FacturaPeer::NUM_COLUMNS - FacturaPeer::NUM_LAZY_LOAD_COLUMNS);

		ClientesPeer::addSelectColumns($c);
		$startcol3 = $startcol2 + (ClientesPeer::NUM_COLUMNS - ClientesPeer::NUM_LAZY_LOAD_COLUMNS);

		VendedorPeer::addSelectColumns($c);
		$startcol4 = $startcol3 + (VendedorPeer::NUM_COLUMNS - VendedorPeer::NUM_LAZY_LOAD_COLUMNS);

		TransporPeer::addSelectColumns($c);
		$startcol5 = $startcol4 + (TransporPeer::NUM_COLUMNS - TransporPeer::NUM_LAZY_LOAD_COLUMNS);

				$c->addJoin(array(FacturaPeer::CO_CLI,), array(ClientesPeer::CO_CLI,), $join_behavior);
				$c->addJoin(array(FacturaPeer::CO_VEN,), array(VendedorPeer::CO_VEN,), $join_behavior);
				$c->addJoin(array(FacturaPeer::CO_TRAN,), array(TransporPeer::CO_TRAN,), $join_behavior);

		$stmt = BasePeer::doSelect($c, $con);
		$results = array();

		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key1 = FacturaPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj1 = FacturaPeer::getInstanceFromPool($key1))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj1->hydrate($row, 0, true); // rehydrate
			} else {
				$omClass = FacturaPeer::getOMClass();

				$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
				$obj1 = new $cls();
				$obj1->hydrate($row);
				FacturaPeer::addInstanceToPool($obj1, $key1);
			} // if obj1 already loaded

				// Add objects for joined Clientes rows

				$key2 = ClientesPeer::getPrimaryKeyHashFromRow($row, $startcol2);
				if ($key2 !== null) {
					$obj2 = ClientesPeer::getInstanceFromPool($key2);
					if (!$obj2) {
	
						$omClass = ClientesPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj2 = new $cls();
					$obj2->hydrate($row, $startcol2);
					ClientesPeer::addInstanceToPool($obj2, $key2);
				} // if $obj2 already loaded

				// Add the $obj1 (Factura) to the collection in $obj2 (Clientes)
				$obj2->addFactura($obj1);

			} // if joined row is not null

				// Add objects for joined Vendedor rows

				$key3 = VendedorPeer::getPrimaryKeyHashFromRow($row, $startcol3);
				if ($key3 !== null) {
					$obj3 = VendedorPeer::getInstanceFromPool($key3);
					if (!$obj3) {
	
						$omClass = VendedorPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj3 = new $cls();
					$obj3->hydrate($row, $startcol3);
					VendedorPeer::addInstanceToPool($obj3, $key3);
				} // if $obj3 already loaded

				// Add the $obj1 (Factura) to the collection in $obj3 (Vendedor)
				$obj3->addFactura($obj1);

			} // if joined row is not null

				// Add objects for joined Transpor rows

				$key4 = TransporPeer::getPrimaryKeyHashFromRow($row, $startcol4);
				if ($key4 !== null) {
					$obj4 = TransporPeer::getInstanceFromPool($key4);
					if (!$obj4) {
	
						$omClass = TransporPeer::getOMClass();


					$cls = substr('.'.$omClass, strrpos('.'.$omClass, '.') + 1);
					$obj4 = new $cls();
					$obj4->hydrate($row, $startcol4);
					TransporPeer::addInstanceToPool($obj4, $key4);
				} // if $obj4 already loaded

				// Add the $obj1 (Factura) to the collection in $obj4 (Transpor)
				$obj4->addFactura($obj1);

			} // if joined row is not null

			$results[] = $obj1;
		}
		$stmt->closeCursor();
		return $results;
	}


  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return FacturaPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a Factura or Criteria object.
	 *
	 * @param      mixed $values Criteria or Factura object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseFacturaPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseFacturaPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(FacturaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Factura object
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseFacturaPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseFacturaPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Factura or Criteria object.
	 *
	 * @param      mixed $values Criteria or Factura object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseFacturaPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseFacturaPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(FacturaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(FacturaPeer::FACT_NUM);
			$selectCriteria->add(FacturaPeer::FACT_NUM, $criteria->remove(FacturaPeer::FACT_NUM), $comparison);

		} else { // $values is Factura object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseFacturaPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseFacturaPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the factura table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(FacturaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(FacturaPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Factura or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Factura object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(FacturaPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			FacturaPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Factura) {
			// invalidate the cache for this single object
			FacturaPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(FacturaPeer::FACT_NUM, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				FacturaPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Factura object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Factura $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Factura $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(FacturaPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(FacturaPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(FacturaPeer::DATABASE_NAME, FacturaPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = FacturaPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Factura
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = FacturaPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(FacturaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(FacturaPeer::DATABASE_NAME);
		$criteria->add(FacturaPeer::FACT_NUM, $pk);

		$v = FacturaPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(FacturaPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(FacturaPeer::DATABASE_NAME);
			$criteria->add(FacturaPeer::FACT_NUM, $pks, Criteria::IN);
			$objs = FacturaPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseFacturaPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the FacturaPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the FacturaPeer class:
//
// Propel::getDatabaseMap(FacturaPeer::DATABASE_NAME)->addTableBuilder(FacturaPeer::TABLE_NAME, FacturaPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseFacturaPeer::DATABASE_NAME)->addTableBuilder(BaseFacturaPeer::TABLE_NAME, BaseFacturaPeer::getMapBuilder());

