<?php

require_once(sfConfig::get('sf_lib_dir').'/filter/base/BaseFormFilterPropel.class.php');

/**
 * DocumCc filter form base class.
 *
 * @package    sf_sandbox
 * @subpackage filter
 * @author     Your name here
 * @version    SVN: $Id: sfPropelFormFilterGeneratedTemplate.php 16976 2009-04-04 12:47:44Z fabien $
 */
class BaseDocumCcFormFilter extends BaseFormFilterPropel
{
  public function setup()
  {
    $this->setWidgets(array(
      'anulado'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'movi'        => new sfWidgetFormFilterInput(),
      'aut'         => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'num_control' => new sfWidgetFormFilterInput(),
      'co_cli'      => new sfWidgetFormPropelChoice(array('model' => 'Clientes', 'add_empty' => true)),
      'contrib'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'fec_emis'    => new sfWidgetFormFilterInput(),
      'fec_venc'    => new sfWidgetFormFilterInput(),
      'observa'     => new sfWidgetFormFilterInput(),
      'doc_orig'    => new sfWidgetFormFilterInput(),
      'nro_orig'    => new sfWidgetFormFilterInput(),
      'co_ban'      => new sfWidgetFormFilterInput(),
      'nro_che'     => new sfWidgetFormFilterInput(),
      'co_ven'      => new sfWidgetFormPropelChoice(array('model' => 'Vendedor', 'add_empty' => true)),
      'tipo'        => new sfWidgetFormPropelChoice(array('model' => 'Tabulado', 'add_empty' => true)),
      'tasa'        => new sfWidgetFormFilterInput(),
      'moneda'      => new sfWidgetFormPropelChoice(array('model' => 'Moneda', 'add_empty' => true)),
      'monto_imp'   => new sfWidgetFormFilterInput(),
      'monto_gen'   => new sfWidgetFormFilterInput(),
      'monto_a1'    => new sfWidgetFormFilterInput(),
      'monto_a2'    => new sfWidgetFormFilterInput(),
      'monto_bru'   => new sfWidgetFormFilterInput(),
      'descuentos'  => new sfWidgetFormFilterInput(),
      'monto_des'   => new sfWidgetFormFilterInput(),
      'recargo'     => new sfWidgetFormFilterInput(),
      'monto_rec'   => new sfWidgetFormFilterInput(),
      'monto_otr'   => new sfWidgetFormFilterInput(),
      'monto_net'   => new sfWidgetFormFilterInput(),
      'saldo'       => new sfWidgetFormFilterInput(),
      'feccom'      => new sfWidgetFormFilterInput(),
      'numcom'      => new sfWidgetFormFilterInput(),
      'dis_cen'     => new sfWidgetFormFilterInput(),
      'comis1'      => new sfWidgetFormFilterInput(),
      'comis2'      => new sfWidgetFormFilterInput(),
      'comis3'      => new sfWidgetFormFilterInput(),
      'comis4'      => new sfWidgetFormFilterInput(),
      'adicional'   => new sfWidgetFormFilterInput(),
      'campo1'      => new sfWidgetFormFilterInput(),
      'campo2'      => new sfWidgetFormFilterInput(),
      'campo3'      => new sfWidgetFormFilterInput(),
      'campo4'      => new sfWidgetFormFilterInput(),
      'campo5'      => new sfWidgetFormFilterInput(),
      'campo6'      => new sfWidgetFormFilterInput(),
      'campo7'      => new sfWidgetFormFilterInput(),
      'campo8'      => new sfWidgetFormFilterInput(),
      'co_us_in'    => new sfWidgetFormFilterInput(),
      'fe_us_in'    => new sfWidgetFormFilterInput(),
      'co_us_mo'    => new sfWidgetFormFilterInput(),
      'fe_us_mo'    => new sfWidgetFormFilterInput(),
      'co_us_el'    => new sfWidgetFormFilterInput(),
      'fe_us_el'    => new sfWidgetFormFilterInput(),
      'revisado'    => new sfWidgetFormFilterInput(),
      'trasnfe'     => new sfWidgetFormFilterInput(),
      'numcon'      => new sfWidgetFormFilterInput(),
      'co_sucu'     => new sfWidgetFormPropelChoice(array('model' => 'Almacen', 'add_empty' => true)),
      'rowguid'     => new sfWidgetFormFilterInput(),
      'mon_ilc'     => new sfWidgetFormFilterInput(),
      'otros1'      => new sfWidgetFormFilterInput(),
      'otros2'      => new sfWidgetFormFilterInput(),
      'otros3'      => new sfWidgetFormFilterInput(),
      'reng_si'     => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'comis5'      => new sfWidgetFormFilterInput(),
      'comis6'      => new sfWidgetFormFilterInput(),
      'row_id'      => new sfWidgetFormFilterInput(),
      'aux01'       => new sfWidgetFormFilterInput(),
      'aux02'       => new sfWidgetFormFilterInput(),
      'salestax'    => new sfWidgetFormFilterInput(),
      'origen'      => new sfWidgetFormFilterInput(),
      'origen_d'    => new sfWidgetFormFilterInput(),
      'fec_reg'     => new sfWidgetFormFilterInput(),
    ));

    $this->setValidators(array(
      'anulado'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'movi'        => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aut'         => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'num_control' => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'co_cli'      => new sfValidatorPropelChoice(array('required' => false, 'model' => 'Clientes', 'column' => 'co_cli')),
      'contrib'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'fec_emis'    => new sfValidatorPass(array('required' => false)),
      'fec_venc'    => new sfValidatorPass(array('required' => false)),
      'observa'     => new sfValidatorPass(array('required' => false)),
      'doc_orig'    => new sfValidatorPass(array('required' => false)),
      'nro_orig'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'co_ban'      => new sfValidatorPass(array('required' => false)),
      'nro_che'     => new sfValidatorPass(array('required' => false)),
      'co_ven'      => new sfValidatorPropelChoice(array('required' => false, 'model' => 'Vendedor', 'column' => 'co_ven')),
      'tipo'        => new sfValidatorPropelChoice(array('required' => false, 'model' => 'Tabulado', 'column' => 'tipo')),
      'tasa'        => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'moneda'      => new sfValidatorPropelChoice(array('required' => false, 'model' => 'Moneda', 'column' => 'co_mone')),
      'monto_imp'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'monto_gen'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'monto_a1'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'monto_a2'    => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'monto_bru'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'descuentos'  => new sfValidatorPass(array('required' => false)),
      'monto_des'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'recargo'     => new sfValidatorPass(array('required' => false)),
      'monto_rec'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'monto_otr'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'monto_net'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'saldo'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'feccom'      => new sfValidatorPass(array('required' => false)),
      'numcom'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'dis_cen'     => new sfValidatorPass(array('required' => false)),
      'comis1'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'comis2'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'comis3'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'comis4'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'adicional'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'campo1'      => new sfValidatorPass(array('required' => false)),
      'campo2'      => new sfValidatorPass(array('required' => false)),
      'campo3'      => new sfValidatorPass(array('required' => false)),
      'campo4'      => new sfValidatorPass(array('required' => false)),
      'campo5'      => new sfValidatorPass(array('required' => false)),
      'campo6'      => new sfValidatorPass(array('required' => false)),
      'campo7'      => new sfValidatorPass(array('required' => false)),
      'campo8'      => new sfValidatorPass(array('required' => false)),
      'co_us_in'    => new sfValidatorPass(array('required' => false)),
      'fe_us_in'    => new sfValidatorPass(array('required' => false)),
      'co_us_mo'    => new sfValidatorPass(array('required' => false)),
      'fe_us_mo'    => new sfValidatorPass(array('required' => false)),
      'co_us_el'    => new sfValidatorPass(array('required' => false)),
      'fe_us_el'    => new sfValidatorPass(array('required' => false)),
      'revisado'    => new sfValidatorPass(array('required' => false)),
      'trasnfe'     => new sfValidatorPass(array('required' => false)),
      'numcon'      => new sfValidatorPass(array('required' => false)),
      'co_sucu'     => new sfValidatorPropelChoice(array('required' => false, 'model' => 'Almacen', 'column' => 'co_alma')),
      'rowguid'     => new sfValidatorPass(array('required' => false)),
      'mon_ilc'     => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'otros1'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'otros2'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'otros3'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'reng_si'     => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'comis5'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'comis6'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'row_id'      => new sfValidatorPass(array('required' => false)),
      'aux01'       => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'aux02'       => new sfValidatorPass(array('required' => false)),
      'salestax'    => new sfValidatorPass(array('required' => false)),
      'origen'      => new sfValidatorPass(array('required' => false)),
      'origen_d'    => new sfValidatorPass(array('required' => false)),
      'fec_reg'     => new sfValidatorPass(array('required' => false)),
    ));

    $this->widgetSchema->setNameFormat('docum_cc_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    parent::setup();
  }

  public function getModelName()
  {
    return 'DocumCc';
  }

  public function getFields()
  {
    return array(
      'tipo_doc'    => 'Text',
      'nro_doc'     => 'Number',
      'anulado'     => 'Boolean',
      'movi'        => 'Number',
      'aut'         => 'Boolean',
      'num_control' => 'Number',
      'co_cli'      => 'ForeignKey',
      'contrib'     => 'Boolean',
      'fec_emis'    => 'Text',
      'fec_venc'    => 'Text',
      'observa'     => 'Text',
      'doc_orig'    => 'Text',
      'nro_orig'    => 'Number',
      'co_ban'      => 'Text',
      'nro_che'     => 'Text',
      'co_ven'      => 'ForeignKey',
      'tipo'        => 'ForeignKey',
      'tasa'        => 'Number',
      'moneda'      => 'ForeignKey',
      'monto_imp'   => 'Number',
      'monto_gen'   => 'Number',
      'monto_a1'    => 'Number',
      'monto_a2'    => 'Number',
      'monto_bru'   => 'Number',
      'descuentos'  => 'Text',
      'monto_des'   => 'Number',
      'recargo'     => 'Text',
      'monto_rec'   => 'Number',
      'monto_otr'   => 'Number',
      'monto_net'   => 'Number',
      'saldo'       => 'Number',
      'feccom'      => 'Text',
      'numcom'      => 'Number',
      'dis_cen'     => 'Text',
      'comis1'      => 'Number',
      'comis2'      => 'Number',
      'comis3'      => 'Number',
      'comis4'      => 'Number',
      'adicional'   => 'Number',
      'campo1'      => 'Text',
      'campo2'      => 'Text',
      'campo3'      => 'Text',
      'campo4'      => 'Text',
      'campo5'      => 'Text',
      'campo6'      => 'Text',
      'campo7'      => 'Text',
      'campo8'      => 'Text',
      'co_us_in'    => 'Text',
      'fe_us_in'    => 'Text',
      'co_us_mo'    => 'Text',
      'fe_us_mo'    => 'Text',
      'co_us_el'    => 'Text',
      'fe_us_el'    => 'Text',
      'revisado'    => 'Text',
      'trasnfe'     => 'Text',
      'numcon'      => 'Text',
      'co_sucu'     => 'ForeignKey',
      'rowguid'     => 'Text',
      'mon_ilc'     => 'Number',
      'otros1'      => 'Number',
      'otros2'      => 'Number',
      'otros3'      => 'Number',
      'reng_si'     => 'Boolean',
      'comis5'      => 'Number',
      'comis6'      => 'Number',
      'row_id'      => 'Text',
      'aux01'       => 'Number',
      'aux02'       => 'Text',
      'salestax'    => 'Text',
      'origen'      => 'Text',
      'origen_d'    => 'Text',
      'fec_reg'     => 'Text',
    );
  }
}
