<?php

require_once(sfConfig::get('sf_lib_dir').'/filter/base/BaseFormFilterPropel.class.php');

/**
 * Prov filter form base class.
 *
 * @package    sf_sandbox
 * @subpackage filter
 * @author     Your name here
 * @version    SVN: $Id: sfPropelFormFilterGeneratedTemplate.php 16976 2009-04-04 12:47:44Z fabien $
 */
class BaseProvFormFilter extends BaseFormFilterPropel
{
  public function setup()
  {
    $this->setWidgets(array(
      'prov_des'   => new sfWidgetFormFilterInput(),
      'co_seg'     => new sfWidgetFormPropelChoice(array('model' => 'Segmento', 'add_empty' => true)),
      'co_zon'     => new sfWidgetFormPropelChoice(array('model' => 'Zona', 'add_empty' => true)),
      'inactivo'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'productos'  => new sfWidgetFormFilterInput(),
      'direc1'     => new sfWidgetFormFilterInput(),
      'direc2'     => new sfWidgetFormFilterInput(),
      'telefonos'  => new sfWidgetFormFilterInput(),
      'fax'        => new sfWidgetFormFilterInput(),
      'respons'    => new sfWidgetFormFilterInput(),
      'fecha_reg'  => new sfWidgetFormFilterInput(),
      'tipo'       => new sfWidgetFormPropelChoice(array('model' => 'TipoPro', 'add_empty' => true)),
      'com_ult_co' => new sfWidgetFormFilterInput(),
      'fec_ult_co' => new sfWidgetFormFilterInput(),
      'net_ult_co' => new sfWidgetFormFilterInput(),
      'saldo'      => new sfWidgetFormFilterInput(),
      'saldo_ini'  => new sfWidgetFormFilterInput(),
      'mont_cre'   => new sfWidgetFormFilterInput(),
      'plaz_pag'   => new sfWidgetFormFilterInput(),
      'desc_ppago' => new sfWidgetFormFilterInput(),
      'desc_glob'  => new sfWidgetFormFilterInput(),
      'tipo_iva'   => new sfWidgetFormFilterInput(),
      'iva'        => new sfWidgetFormFilterInput(),
      'rif'        => new sfWidgetFormFilterInput(),
      'nacional'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'dis_cen'    => new sfWidgetFormFilterInput(),
      'nit'        => new sfWidgetFormFilterInput(),
      'email'      => new sfWidgetFormFilterInput(),
      'co_ingr'    => new sfWidgetFormPropelChoice(array('model' => 'CtaIngr', 'add_empty' => true)),
      'comentario' => new sfWidgetFormFilterInput(),
      'campo1'     => new sfWidgetFormFilterInput(),
      'campo2'     => new sfWidgetFormFilterInput(),
      'campo3'     => new sfWidgetFormFilterInput(),
      'campo4'     => new sfWidgetFormFilterInput(),
      'campo5'     => new sfWidgetFormFilterInput(),
      'campo6'     => new sfWidgetFormFilterInput(),
      'campo7'     => new sfWidgetFormFilterInput(),
      'campo8'     => new sfWidgetFormFilterInput(),
      'co_us_in'   => new sfWidgetFormFilterInput(),
      'fe_us_in'   => new sfWidgetFormFilterInput(),
      'co_us_mo'   => new sfWidgetFormFilterInput(),
      'fe_us_mo'   => new sfWidgetFormFilterInput(),
      'co_us_el'   => new sfWidgetFormFilterInput(),
      'fe_us_el'   => new sfWidgetFormFilterInput(),
      'revisado'   => new sfWidgetFormFilterInput(),
      'trasnfe'    => new sfWidgetFormFilterInput(),
      'co_sucu'    => new sfWidgetFormFilterInput(),
      'rowguid'    => new sfWidgetFormFilterInput(),
      'juridico'   => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'tipo_adi'   => new sfWidgetFormFilterInput(),
      'matriz'     => new sfWidgetFormFilterInput(),
      'co_tab'     => new sfWidgetFormFilterInput(),
      'tipo_per'   => new sfWidgetFormFilterInput(),
      'co_pais'    => new sfWidgetFormFilterInput(),
      'ciudad'     => new sfWidgetFormFilterInput(),
      'zip'        => new sfWidgetFormFilterInput(),
      'website'    => new sfWidgetFormFilterInput(),
      'formtype'   => new sfWidgetFormFilterInput(),
      'taxid'      => new sfWidgetFormFilterInput(),
      'contribu_e' => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'porc_esp'   => new sfWidgetFormFilterInput(),
    ));

    $this->setValidators(array(
      'prov_des'   => new sfValidatorPass(array('required' => false)),
      'co_seg'     => new sfValidatorPropelChoice(array('required' => false, 'model' => 'Segmento', 'column' => 'co_seg')),
      'co_zon'     => new sfValidatorPropelChoice(array('required' => false, 'model' => 'Zona', 'column' => 'co_zon')),
      'inactivo'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'productos'  => new sfValidatorPass(array('required' => false)),
      'direc1'     => new sfValidatorPass(array('required' => false)),
      'direc2'     => new sfValidatorPass(array('required' => false)),
      'telefonos'  => new sfValidatorPass(array('required' => false)),
      'fax'        => new sfValidatorPass(array('required' => false)),
      'respons'    => new sfValidatorPass(array('required' => false)),
      'fecha_reg'  => new sfValidatorPass(array('required' => false)),
      'tipo'       => new sfValidatorPropelChoice(array('required' => false, 'model' => 'TipoPro', 'column' => 'tip_pro')),
      'com_ult_co' => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fec_ult_co' => new sfValidatorPass(array('required' => false)),
      'net_ult_co' => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'saldo'      => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'saldo_ini'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'mont_cre'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'plaz_pag'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'desc_ppago' => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'desc_glob'  => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'tipo_iva'   => new sfValidatorPass(array('required' => false)),
      'iva'        => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'rif'        => new sfValidatorPass(array('required' => false)),
      'nacional'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'dis_cen'    => new sfValidatorPass(array('required' => false)),
      'nit'        => new sfValidatorPass(array('required' => false)),
      'email'      => new sfValidatorPass(array('required' => false)),
      'co_ingr'    => new sfValidatorPropelChoice(array('required' => false, 'model' => 'CtaIngr', 'column' => 'co_ingr')),
      'comentario' => new sfValidatorPass(array('required' => false)),
      'campo1'     => new sfValidatorPass(array('required' => false)),
      'campo2'     => new sfValidatorPass(array('required' => false)),
      'campo3'     => new sfValidatorPass(array('required' => false)),
      'campo4'     => new sfValidatorPass(array('required' => false)),
      'campo5'     => new sfValidatorPass(array('required' => false)),
      'campo6'     => new sfValidatorPass(array('required' => false)),
      'campo7'     => new sfValidatorPass(array('required' => false)),
      'campo8'     => new sfValidatorPass(array('required' => false)),
      'co_us_in'   => new sfValidatorPass(array('required' => false)),
      'fe_us_in'   => new sfValidatorPass(array('required' => false)),
      'co_us_mo'   => new sfValidatorPass(array('required' => false)),
      'fe_us_mo'   => new sfValidatorPass(array('required' => false)),
      'co_us_el'   => new sfValidatorPass(array('required' => false)),
      'fe_us_el'   => new sfValidatorPass(array('required' => false)),
      'revisado'   => new sfValidatorPass(array('required' => false)),
      'trasnfe'    => new sfValidatorPass(array('required' => false)),
      'co_sucu'    => new sfValidatorPass(array('required' => false)),
      'rowguid'    => new sfValidatorPass(array('required' => false)),
      'juridico'   => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'tipo_adi'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
      'matriz'     => new sfValidatorPass(array('required' => false)),
      'co_tab'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tipo_per'   => new sfValidatorPass(array('required' => false)),
      'co_pais'    => new sfValidatorPass(array('required' => false)),
      'ciudad'     => new sfValidatorPass(array('required' => false)),
      'zip'        => new sfValidatorPass(array('required' => false)),
      'website'    => new sfValidatorPass(array('required' => false)),
      'formtype'   => new sfValidatorPass(array('required' => false)),
      'taxid'      => new sfValidatorPass(array('required' => false)),
      'contribu_e' => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'porc_esp'   => new sfValidatorSchemaFilter('text', new sfValidatorNumber(array('required' => false))),
    ));

    $this->widgetSchema->setNameFormat('prov_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    parent::setup();
  }

  public function getModelName()
  {
    return 'Prov';
  }

  public function getFields()
  {
    return array(
      'co_prov'    => 'Text',
      'prov_des'   => 'Text',
      'co_seg'     => 'ForeignKey',
      'co_zon'     => 'ForeignKey',
      'inactivo'   => 'Boolean',
      'productos'  => 'Text',
      'direc1'     => 'Text',
      'direc2'     => 'Text',
      'telefonos'  => 'Text',
      'fax'        => 'Text',
      'respons'    => 'Text',
      'fecha_reg'  => 'Text',
      'tipo'       => 'ForeignKey',
      'com_ult_co' => 'Number',
      'fec_ult_co' => 'Text',
      'net_ult_co' => 'Number',
      'saldo'      => 'Number',
      'saldo_ini'  => 'Number',
      'mont_cre'   => 'Number',
      'plaz_pag'   => 'Number',
      'desc_ppago' => 'Number',
      'desc_glob'  => 'Number',
      'tipo_iva'   => 'Text',
      'iva'        => 'Number',
      'rif'        => 'Text',
      'nacional'   => 'Boolean',
      'dis_cen'    => 'Text',
      'nit'        => 'Text',
      'email'      => 'Text',
      'co_ingr'    => 'ForeignKey',
      'comentario' => 'Text',
      'campo1'     => 'Text',
      'campo2'     => 'Text',
      'campo3'     => 'Text',
      'campo4'     => 'Text',
      'campo5'     => 'Text',
      'campo6'     => 'Text',
      'campo7'     => 'Text',
      'campo8'     => 'Text',
      'co_us_in'   => 'Text',
      'fe_us_in'   => 'Text',
      'co_us_mo'   => 'Text',
      'fe_us_mo'   => 'Text',
      'co_us_el'   => 'Text',
      'fe_us_el'   => 'Text',
      'revisado'   => 'Text',
      'trasnfe'    => 'Text',
      'co_sucu'    => 'Text',
      'rowguid'    => 'Text',
      'juridico'   => 'Boolean',
      'tipo_adi'   => 'Number',
      'matriz'     => 'Text',
      'co_tab'     => 'Number',
      'tipo_per'   => 'Text',
      'co_pais'    => 'Text',
      'ciudad'     => 'Text',
      'zip'        => 'Text',
      'website'    => 'Text',
      'formtype'   => 'Text',
      'taxid'      => 'Text',
      'contribu_e' => 'Boolean',
      'porc_esp'   => 'Number',
    );
  }
}
