<?php

require_once(sfConfig::get('sf_lib_dir').'/filter/base/BaseFormFilterPropel.class.php');

/**
 * Almacen filter form base class.
 *
 * @package    sf_sandbox
 * @subpackage filter
 * @author     Your name here
 * @version    SVN: $Id: sfPropelFormFilterGeneratedTemplate.php 16976 2009-04-04 12:47:44Z fabien $
 */
class BaseAlmacenFormFilter extends BaseFormFilterPropel
{
  public function setup()
  {
    $this->setWidgets(array(
      'alma_des'    => new sfWidgetFormFilterInput(),
      'nro_fact'    => new sfWidgetFormFilterInput(),
      'num_fac_ini' => new sfWidgetFormFilterInput(),
      'num_fac_fin' => new sfWidgetFormFilterInput(),
      'campo1'      => new sfWidgetFormFilterInput(),
      'campo2'      => new sfWidgetFormFilterInput(),
      'campo3'      => new sfWidgetFormFilterInput(),
      'campo4'      => new sfWidgetFormFilterInput(),
      'co_us_in'    => new sfWidgetFormFilterInput(),
      'fe_us_in'    => new sfWidgetFormFilterInput(),
      'co_us_mo'    => new sfWidgetFormFilterInput(),
      'fe_us_mo'    => new sfWidgetFormFilterInput(),
      'co_us_el'    => new sfWidgetFormFilterInput(),
      'fe_us_el'    => new sfWidgetFormFilterInput(),
      'revisado'    => new sfWidgetFormFilterInput(),
      'trasnfe'     => new sfWidgetFormFilterInput(),
      'co_sucu'     => new sfWidgetFormFilterInput(),
      'rowguid'     => new sfWidgetFormFilterInput(),
      'nc_num'      => new sfWidgetFormFilterInput(),
      'nd_num'      => new sfWidgetFormFilterInput(),
      'ajus_num'    => new sfWidgetFormFilterInput(),
      'tras_num'    => new sfWidgetFormFilterInput(),
      'fisi_num'    => new sfWidgetFormFilterInput(),
      'num_kit'     => new sfWidgetFormFilterInput(),
      'genk_num'    => new sfWidgetFormFilterInput(),
      'fact_num'    => new sfWidgetFormFilterInput(),
      'ped_num'     => new sfWidgetFormFilterInput(),
      'cotc_num'    => new sfWidgetFormFilterInput(),
      'devc_num'    => new sfWidgetFormFilterInput(),
      'nde_num'     => new sfWidgetFormFilterInput(),
      'ndd_num'     => new sfWidgetFormFilterInput(),
      'post_num'    => new sfWidgetFormFilterInput(),
      'cfxg_num'    => new sfWidgetFormFilterInput(),
      'chdv_num'    => new sfWidgetFormFilterInput(),
      'giro_num'    => new sfWidgetFormFilterInput(),
      'reten_num'   => new sfWidgetFormFilterInput(),
      'cb_num'      => new sfWidgetFormFilterInput(),
      'movb_num'    => new sfWidgetFormFilterInput(),
      'movc_num'    => new sfWidgetFormFilterInput(),
      'ordp_num'    => new sfWidgetFormFilterInput(),
      'depc_num'    => new sfWidgetFormFilterInput(),
      'comp_num'    => new sfWidgetFormFilterInput(),
      'ord_num'     => new sfWidgetFormFilterInput(),
      'cotp_num'    => new sfWidgetFormFilterInput(),
      'devp_num'    => new sfWidgetFormFilterInput(),
      'ndr_num'     => new sfWidgetFormFilterInput(),
      'postcppnum'  => new sfWidgetFormFilterInput(),
      'ccxg_num'    => new sfWidgetFormFilterInput(),
      'chdvcppnum'  => new sfWidgetFormFilterInput(),
      'girocppnum'  => new sfWidgetFormFilterInput(),
      'nccpp_num'   => new sfWidgetFormFilterInput(),
      'ndcpp_num'   => new sfWidgetFormFilterInput(),
      'retencppnum' => new sfWidgetFormFilterInput(),
      'pg_num'      => new sfWidgetFormFilterInput(),
      'aju_posm'    => new sfWidgetFormFilterInput(),
      'aju_posa'    => new sfWidgetFormFilterInput(),
      'aju_negm'    => new sfWidgetFormFilterInput(),
      'aju_nega'    => new sfWidgetFormFilterInput(),
      'aju_posmc'   => new sfWidgetFormFilterInput(),
      'aju_posac'   => new sfWidgetFormFilterInput(),
      'aju_negmc'   => new sfWidgetFormFilterInput(),
      'aju_negac'   => new sfWidgetFormFilterInput(),
      'pventa'      => new sfWidgetFormFilterInput(),
      'turnosic'    => new sfWidgetFormFilterInput(),
      'plv_num'     => new sfWidgetFormFilterInput(),
      'plc_num'     => new sfWidgetFormFilterInput(),
      'tabislr'     => new sfWidgetFormFilterInput(),
      'imp_num'     => new sfWidgetFormFilterInput(),
      'rma_cli'     => new sfWidgetFormFilterInput(),
      'rma_prov'    => new sfWidgetFormFilterInput(),
      'rma_entc'    => new sfWidgetFormFilterInput(),
      'rma_entp'    => new sfWidgetFormFilterInput(),
      'rma_regs'    => new sfWidgetFormFilterInput(),
      'fact_s1'     => new sfWidgetFormFilterInput(),
      'fact_s2'     => new sfWidgetFormFilterInput(),
      'fact_s3'     => new sfWidgetFormFilterInput(),
      'fact_s4'     => new sfWidgetFormFilterInput(),
      'fact_s5'     => new sfWidgetFormFilterInput(),
      'nde_s1'      => new sfWidgetFormFilterInput(),
      'nde_s2'      => new sfWidgetFormFilterInput(),
      'nde_s3'      => new sfWidgetFormFilterInput(),
      'nde_s4'      => new sfWidgetFormFilterInput(),
      'nde_s5'      => new sfWidgetFormFilterInput(),
      'nc_s1'       => new sfWidgetFormFilterInput(),
      'nc_s2'       => new sfWidgetFormFilterInput(),
      'nc_s3'       => new sfWidgetFormFilterInput(),
      'nc_s4'       => new sfWidgetFormFilterInput(),
      'nc_s5'       => new sfWidgetFormFilterInput(),
      'nd_s1'       => new sfWidgetFormFilterInput(),
      'nd_s2'       => new sfWidgetFormFilterInput(),
      'nd_s3'       => new sfWidgetFormFilterInput(),
      'nd_s4'       => new sfWidgetFormFilterInput(),
      'nd_s5'       => new sfWidgetFormFilterInput(),
      'fact_f1'     => new sfWidgetFormFilterInput(),
      'fact_f2'     => new sfWidgetFormFilterInput(),
      'fact_f3'     => new sfWidgetFormFilterInput(),
      'fact_f4'     => new sfWidgetFormFilterInput(),
      'nde_f1'      => new sfWidgetFormFilterInput(),
      'nde_f2'      => new sfWidgetFormFilterInput(),
      'nde_f3'      => new sfWidgetFormFilterInput(),
      'nde_f4'      => new sfWidgetFormFilterInput(),
      'nc_f1'       => new sfWidgetFormFilterInput(),
      'nc_f2'       => new sfWidgetFormFilterInput(),
      'nc_f3'       => new sfWidgetFormFilterInput(),
      'nc_f4'       => new sfWidgetFormFilterInput(),
      'nd_f1'       => new sfWidgetFormFilterInput(),
      'nd_f2'       => new sfWidgetFormFilterInput(),
      'nd_f3'       => new sfWidgetFormFilterInput(),
      'nd_f4'       => new sfWidgetFormFilterInput(),
      'fact_p1'     => new sfWidgetFormFilterInput(),
      'fact_p2'     => new sfWidgetFormFilterInput(),
      'fact_p3'     => new sfWidgetFormFilterInput(),
      'fact_p4'     => new sfWidgetFormFilterInput(),
      'fact_p5'     => new sfWidgetFormFilterInput(),
      'nde_p1'      => new sfWidgetFormFilterInput(),
      'nde_p2'      => new sfWidgetFormFilterInput(),
      'nde_p3'      => new sfWidgetFormFilterInput(),
      'nde_p4'      => new sfWidgetFormFilterInput(),
      'nde_p5'      => new sfWidgetFormFilterInput(),
      'nc_p1'       => new sfWidgetFormFilterInput(),
      'nc_p2'       => new sfWidgetFormFilterInput(),
      'nc_p3'       => new sfWidgetFormFilterInput(),
      'nc_p4'       => new sfWidgetFormFilterInput(),
      'nc_p5'       => new sfWidgetFormFilterInput(),
      'nd_p1'       => new sfWidgetFormFilterInput(),
      'nd_p2'       => new sfWidgetFormFilterInput(),
      'nd_p3'       => new sfWidgetFormFilterInput(),
      'nd_p4'       => new sfWidgetFormFilterInput(),
      'nd_p5'       => new sfWidgetFormFilterInput(),
      'fact_num2'   => new sfWidgetFormFilterInput(),
      'fact_num3'   => new sfWidgetFormFilterInput(),
      'fact_num4'   => new sfWidgetFormFilterInput(),
      'fact_num5'   => new sfWidgetFormFilterInput(),
      'nde_num2'    => new sfWidgetFormFilterInput(),
      'nde_num3'    => new sfWidgetFormFilterInput(),
      'nde_num4'    => new sfWidgetFormFilterInput(),
      'nde_num5'    => new sfWidgetFormFilterInput(),
      'nc_num2'     => new sfWidgetFormFilterInput(),
      'nc_num3'     => new sfWidgetFormFilterInput(),
      'nc_num4'     => new sfWidgetFormFilterInput(),
      'nc_num5'     => new sfWidgetFormFilterInput(),
      'nd_num2'     => new sfWidgetFormFilterInput(),
      'nd_num3'     => new sfWidgetFormFilterInput(),
      'nd_num4'     => new sfWidgetFormFilterInput(),
      'nd_num5'     => new sfWidgetFormFilterInput(),
      'serie2'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'serie3'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'serie4'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'serie5'      => new sfWidgetFormChoice(array('choices' => array('' => 'yes or no', 1 => 'yes', 0 => 'no'))),
      'emp_num'     => new sfWidgetFormFilterInput(),
      'dmc_num'     => new sfWidgetFormFilterInput(),
      'tax_num'     => new sfWidgetFormFilterInput(),
      'ced_num'     => new sfWidgetFormFilterInput(),
      'ent_num'     => new sfWidgetFormFilterInput(),
      'cie_num'     => new sfWidgetFormFilterInput(),
      'odp_num'     => new sfWidgetFormFilterInput(),
      'req_num'     => new sfWidgetFormFilterInput(),
      'dev_num'     => new sfWidgetFormFilterInput(),
      'exp_num'     => new sfWidgetFormFilterInput(),
      'inp_num'     => new sfWidgetFormFilterInput(),
      'cost_num'    => new sfWidgetFormFilterInput(),
      'par_num'     => new sfWidgetFormFilterInput(),
      'esc_num'     => new sfWidgetFormFilterInput(),
      'pla_num'     => new sfWidgetFormFilterInput(),
      'men_num'     => new sfWidgetFormFilterInput(),
      'dist_num'    => new sfWidgetFormFilterInput(),
      'exp_numi'    => new sfWidgetFormFilterInput(),
    ));

    $this->setValidators(array(
      'alma_des'    => new sfValidatorPass(array('required' => false)),
      'nro_fact'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'num_fac_ini' => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'num_fac_fin' => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'campo1'      => new sfValidatorPass(array('required' => false)),
      'campo2'      => new sfValidatorPass(array('required' => false)),
      'campo3'      => new sfValidatorPass(array('required' => false)),
      'campo4'      => new sfValidatorPass(array('required' => false)),
      'co_us_in'    => new sfValidatorPass(array('required' => false)),
      'fe_us_in'    => new sfValidatorPass(array('required' => false)),
      'co_us_mo'    => new sfValidatorPass(array('required' => false)),
      'fe_us_mo'    => new sfValidatorPass(array('required' => false)),
      'co_us_el'    => new sfValidatorPass(array('required' => false)),
      'fe_us_el'    => new sfValidatorPass(array('required' => false)),
      'revisado'    => new sfValidatorPass(array('required' => false)),
      'trasnfe'     => new sfValidatorPass(array('required' => false)),
      'co_sucu'     => new sfValidatorPass(array('required' => false)),
      'rowguid'     => new sfValidatorPass(array('required' => false)),
      'nc_num'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nd_num'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ajus_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tras_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fisi_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'num_kit'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'genk_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fact_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ped_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cotc_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'devc_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nde_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ndd_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'post_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cfxg_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'chdv_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'giro_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'reten_num'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cb_num'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'movb_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'movc_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ordp_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'depc_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'comp_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ord_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cotp_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'devp_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ndr_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'postcppnum'  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ccxg_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'chdvcppnum'  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'girocppnum'  => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nccpp_num'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ndcpp_num'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'retencppnum' => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pg_num'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aju_posm'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aju_posa'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aju_negm'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aju_nega'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aju_posmc'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aju_posac'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aju_negmc'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'aju_negac'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pventa'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'turnosic'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'plv_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'plc_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tabislr'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'imp_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'rma_cli'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'rma_prov'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'rma_entc'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'rma_entp'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'rma_regs'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fact_s1'     => new sfValidatorPass(array('required' => false)),
      'fact_s2'     => new sfValidatorPass(array('required' => false)),
      'fact_s3'     => new sfValidatorPass(array('required' => false)),
      'fact_s4'     => new sfValidatorPass(array('required' => false)),
      'fact_s5'     => new sfValidatorPass(array('required' => false)),
      'nde_s1'      => new sfValidatorPass(array('required' => false)),
      'nde_s2'      => new sfValidatorPass(array('required' => false)),
      'nde_s3'      => new sfValidatorPass(array('required' => false)),
      'nde_s4'      => new sfValidatorPass(array('required' => false)),
      'nde_s5'      => new sfValidatorPass(array('required' => false)),
      'nc_s1'       => new sfValidatorPass(array('required' => false)),
      'nc_s2'       => new sfValidatorPass(array('required' => false)),
      'nc_s3'       => new sfValidatorPass(array('required' => false)),
      'nc_s4'       => new sfValidatorPass(array('required' => false)),
      'nc_s5'       => new sfValidatorPass(array('required' => false)),
      'nd_s1'       => new sfValidatorPass(array('required' => false)),
      'nd_s2'       => new sfValidatorPass(array('required' => false)),
      'nd_s3'       => new sfValidatorPass(array('required' => false)),
      'nd_s4'       => new sfValidatorPass(array('required' => false)),
      'nd_s5'       => new sfValidatorPass(array('required' => false)),
      'fact_f1'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fact_f2'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fact_f3'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fact_f4'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nde_f1'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nde_f2'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nde_f3'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nde_f4'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nc_f1'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nc_f2'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nc_f3'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nc_f4'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nd_f1'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nd_f2'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nd_f3'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nd_f4'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fact_p1'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fact_p2'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fact_p3'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fact_p4'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fact_p5'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nde_p1'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nde_p2'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nde_p3'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nde_p4'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nde_p5'      => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nc_p1'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nc_p2'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nc_p3'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nc_p4'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nc_p5'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nd_p1'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nd_p2'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nd_p3'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nd_p4'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nd_p5'       => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fact_num2'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fact_num3'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fact_num4'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'fact_num5'   => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nde_num2'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nde_num3'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nde_num4'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nde_num5'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nc_num2'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nc_num3'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nc_num4'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nc_num5'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nd_num2'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nd_num3'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nd_num4'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'nd_num5'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'serie2'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'serie3'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'serie4'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'serie5'      => new sfValidatorChoice(array('required' => false, 'choices' => array('', 1, 0))),
      'emp_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'dmc_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'tax_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ced_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'ent_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cie_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'odp_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'req_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'dev_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'exp_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'inp_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'cost_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'par_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'esc_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'pla_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'men_num'     => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'dist_num'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
      'exp_numi'    => new sfValidatorSchemaFilter('text', new sfValidatorInteger(array('required' => false))),
    ));

    $this->widgetSchema->setNameFormat('almacen_filters[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    parent::setup();
  }

  public function getModelName()
  {
    return 'Almacen';
  }

  public function getFields()
  {
    return array(
      'co_alma'     => 'Text',
      'alma_des'    => 'Text',
      'nro_fact'    => 'Number',
      'num_fac_ini' => 'Number',
      'num_fac_fin' => 'Number',
      'campo1'      => 'Text',
      'campo2'      => 'Text',
      'campo3'      => 'Text',
      'campo4'      => 'Text',
      'co_us_in'    => 'Text',
      'fe_us_in'    => 'Text',
      'co_us_mo'    => 'Text',
      'fe_us_mo'    => 'Text',
      'co_us_el'    => 'Text',
      'fe_us_el'    => 'Text',
      'revisado'    => 'Text',
      'trasnfe'     => 'Text',
      'co_sucu'     => 'Text',
      'rowguid'     => 'Text',
      'nc_num'      => 'Number',
      'nd_num'      => 'Number',
      'ajus_num'    => 'Number',
      'tras_num'    => 'Number',
      'fisi_num'    => 'Number',
      'num_kit'     => 'Number',
      'genk_num'    => 'Number',
      'fact_num'    => 'Number',
      'ped_num'     => 'Number',
      'cotc_num'    => 'Number',
      'devc_num'    => 'Number',
      'nde_num'     => 'Number',
      'ndd_num'     => 'Number',
      'post_num'    => 'Number',
      'cfxg_num'    => 'Number',
      'chdv_num'    => 'Number',
      'giro_num'    => 'Number',
      'reten_num'   => 'Number',
      'cb_num'      => 'Number',
      'movb_num'    => 'Number',
      'movc_num'    => 'Number',
      'ordp_num'    => 'Number',
      'depc_num'    => 'Number',
      'comp_num'    => 'Number',
      'ord_num'     => 'Number',
      'cotp_num'    => 'Number',
      'devp_num'    => 'Number',
      'ndr_num'     => 'Number',
      'postcppnum'  => 'Number',
      'ccxg_num'    => 'Number',
      'chdvcppnum'  => 'Number',
      'girocppnum'  => 'Number',
      'nccpp_num'   => 'Number',
      'ndcpp_num'   => 'Number',
      'retencppnum' => 'Number',
      'pg_num'      => 'Number',
      'aju_posm'    => 'Number',
      'aju_posa'    => 'Number',
      'aju_negm'    => 'Number',
      'aju_nega'    => 'Number',
      'aju_posmc'   => 'Number',
      'aju_posac'   => 'Number',
      'aju_negmc'   => 'Number',
      'aju_negac'   => 'Number',
      'pventa'      => 'Number',
      'turnosic'    => 'Number',
      'plv_num'     => 'Number',
      'plc_num'     => 'Number',
      'tabislr'     => 'Number',
      'imp_num'     => 'Number',
      'rma_cli'     => 'Number',
      'rma_prov'    => 'Number',
      'rma_entc'    => 'Number',
      'rma_entp'    => 'Number',
      'rma_regs'    => 'Number',
      'fact_s1'     => 'Text',
      'fact_s2'     => 'Text',
      'fact_s3'     => 'Text',
      'fact_s4'     => 'Text',
      'fact_s5'     => 'Text',
      'nde_s1'      => 'Text',
      'nde_s2'      => 'Text',
      'nde_s3'      => 'Text',
      'nde_s4'      => 'Text',
      'nde_s5'      => 'Text',
      'nc_s1'       => 'Text',
      'nc_s2'       => 'Text',
      'nc_s3'       => 'Text',
      'nc_s4'       => 'Text',
      'nc_s5'       => 'Text',
      'nd_s1'       => 'Text',
      'nd_s2'       => 'Text',
      'nd_s3'       => 'Text',
      'nd_s4'       => 'Text',
      'nd_s5'       => 'Text',
      'fact_f1'     => 'Number',
      'fact_f2'     => 'Number',
      'fact_f3'     => 'Number',
      'fact_f4'     => 'Number',
      'nde_f1'      => 'Number',
      'nde_f2'      => 'Number',
      'nde_f3'      => 'Number',
      'nde_f4'      => 'Number',
      'nc_f1'       => 'Number',
      'nc_f2'       => 'Number',
      'nc_f3'       => 'Number',
      'nc_f4'       => 'Number',
      'nd_f1'       => 'Number',
      'nd_f2'       => 'Number',
      'nd_f3'       => 'Number',
      'nd_f4'       => 'Number',
      'fact_p1'     => 'Number',
      'fact_p2'     => 'Number',
      'fact_p3'     => 'Number',
      'fact_p4'     => 'Number',
      'fact_p5'     => 'Number',
      'nde_p1'      => 'Number',
      'nde_p2'      => 'Number',
      'nde_p3'      => 'Number',
      'nde_p4'      => 'Number',
      'nde_p5'      => 'Number',
      'nc_p1'       => 'Number',
      'nc_p2'       => 'Number',
      'nc_p3'       => 'Number',
      'nc_p4'       => 'Number',
      'nc_p5'       => 'Number',
      'nd_p1'       => 'Number',
      'nd_p2'       => 'Number',
      'nd_p3'       => 'Number',
      'nd_p4'       => 'Number',
      'nd_p5'       => 'Number',
      'fact_num2'   => 'Number',
      'fact_num3'   => 'Number',
      'fact_num4'   => 'Number',
      'fact_num5'   => 'Number',
      'nde_num2'    => 'Number',
      'nde_num3'    => 'Number',
      'nde_num4'    => 'Number',
      'nde_num5'    => 'Number',
      'nc_num2'     => 'Number',
      'nc_num3'     => 'Number',
      'nc_num4'     => 'Number',
      'nc_num5'     => 'Number',
      'nd_num2'     => 'Number',
      'nd_num3'     => 'Number',
      'nd_num4'     => 'Number',
      'nd_num5'     => 'Number',
      'serie2'      => 'Boolean',
      'serie3'      => 'Boolean',
      'serie4'      => 'Boolean',
      'serie5'      => 'Boolean',
      'emp_num'     => 'Number',
      'dmc_num'     => 'Number',
      'tax_num'     => 'Number',
      'ced_num'     => 'Number',
      'ent_num'     => 'Number',
      'cie_num'     => 'Number',
      'odp_num'     => 'Number',
      'req_num'     => 'Number',
      'dev_num'     => 'Number',
      'exp_num'     => 'Number',
      'inp_num'     => 'Number',
      'cost_num'    => 'Number',
      'par_num'     => 'Number',
      'esc_num'     => 'Number',
      'pla_num'     => 'Number',
      'men_num'     => 'Number',
      'dist_num'    => 'Number',
      'exp_numi'    => 'Number',
    );
  }
}
