multipartinbox:
  class: sfPropelRouteCollection
  options:
    model:                Multipartinbox
    module:               multipartinbox
    prefix_path:          multipartinbox
    column:               id
    with_wildcard_routes: true

outbox:
  class: sfPropelRouteCollection
  options:
    model:                Outbox
    module:               outbox
    prefix_path:          outbox
    column:               id
    with_wildcard_routes: true

enviados:
  class: sfPropelRouteCollection
  options:
    model:                Outbox
    module:               enviados
    prefix_path:          enviados
    column:               id
    with_wildcard_routes: true


inbox:
  class: sfPropelRouteCollection
  options:
    model:                Inbox
    module:               inbox
    prefix_path:          inbox
    column:               id
    with_wildcard_routes: true

clientes:
  class: sfPropelRouteCollection
  options:
    model:                Clientes
    module:               clientes
    prefix_path:          clientes
    column:               co_cli
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: default, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
