default:
  http_metas:
    content-type: text/html

  metas:
    title:        Envío SMS - Cobranza
    description:  envio de sms a clientes morosos
    keywords:     envio sms clientes morosos
    language:     es_VE
    robots:       index, follow

  stylesheets:    [main.css]

  javascripts:    []

  has_layout:     on
  layout:         layout
