default:
  http_metas:
    content-type: text/html

  metas:
    title:        Gestión de Cobranza - Agencia Royal 33 C.A.
    description:  gestion de cobranza agencia royal 33
    keywords:     envio sms clientes morosos agencia royal gestion cobranza
    language:     es_VE
    robots:       index, follow

  stylesheets:    [main.css, /sf/calendar/skins/aqua/theme.css, main_jobeet.css, jobs.css]

  javascripts:    [/sf/calendar/calendar.js, /sf/calendar/lang/calendar-es.js, /sf/calendar/calendar-setup.js]

  has_layout:     on
  layout:         layoutv2
