opciones:                  # Opciones generales
  eliminar:                false
  tabla:                   docum_cc
  anchogrid:               800
  ancho:                   600
  filas:                   0
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Enviar
  tipo:                    k
  nombrecampo:             enviar
  html:                    [size="5" ]
  esgrabable:              true
2:       # Columna 3
  titulo:                  Cedula Cliente
  tipo:                    t
  nombrecampo:             co_cli
  html:                    [size="6" readonly=true ]
  esgrabable:              true
3:       # Columna 4
  titulo:                  Nombre
  tipo:                    t
  nombrecampo:             nom_cli
  html:                    [size="19" readonly=true ]
4:       # Columna 5
  titulo:                  Vencimiento
  tipo:                    t
  nombrecampo:             fec_venc
  html:                    [size="8" readonly=true ]
5:       # Columna 6
  titulo:                  Monto
  tipo:                    m
  nombrecampo:             monto_net
  html:                    [size="5" readonly=true ]
  estotal:                 [true, totalp]
6:       # Columna 7
  titulo:                  Observacion
  tipo:                    t
  nombrecampo:             observa
  html:                    [size="19" readonly=true ]
7:       # Columna 7
  titulo:                  Celular
  tipo:                    t
  nombrecampo:             celular
  html:                    [size="12" readonly=true ]
  esgrabable:              true
8:       # Columna 8
  titulo:                  Telefono
  tipo:                    t
  nombrecampo:             telefono
  html:                    [size="12" readonly=true ]
  esgrabable:              true
9:       # Columna 8
  titulo:                  Vendedor
  tipo:                    t
  nombrecampo:             nomven
  html:                    [size="12" readonly=true ]
  esgrabable:              true


