opciones:                  # Opciones generales
  eliminar:                false
  tabla:                   docum_cc
  anchogrid:               700
  ancho:                   400
  filas:                   0
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Enviar
  tipo:                    k
  nombrecampo:             enviar
  html:                    [size="5" ]
2:       # Columna 2
  titulo:                  Tipo
  tipo:                    t
  nombrecampo:             tipo_doc
  html:                    [size="10" ]
3:       # Columna 3
  titulo:                  Cedula Cliente
  tipo:                    t
  nombrecampo:             co_cli
  html:                    [size="10" ]
4:       # Columna 4
  titulo:                  Nro. Documento
  tipo:                    t
  nombrecampo:             nro_doc
  html:                    [size="10" ]


