opciones:                  # Opciones generales
  eliminar:                false
  tabla:                   clientes
  anchogrid:               700
  ancho:                   400
  filas:                   0
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 1
  titulo:                  Aprobado
  tipo:                    k
  nombrecampo:             aprobado
  html:                    [size="5" ]
2:       # Columna 2
  titulo:                  Cliente
  tipo:                    t
  nombrecampo:             co_cli
  html:                    [size="10" ]
3:       # Columna 3
  titulo:                  Nombre
  tipo:                    t
  nombrecampo:             cli_des
  html:                    [size="40" ]


