opciones:                  # Opciones generales
  eliminar:                false
  tabla:                   cobro
  anchogrid:               600
  ancho:                   580
  filas:                   0
  titulo:                  ' '
  htmltotalfilas:          ' '
1:       # Columna 3
  titulo:                  Nro. Pago
  tipo:                    t
  nombrecampo:             cob_num
  html:                    [size="6" readonly=true ]
  esgrabable:              true
2:       # Columna 3
  titulo:                  Cedula Cliente
  tipo:                    t
  nombrecampo:             co_cli
  html:                    [size="6" readonly=true ]
  esgrabable:              true
3:       # Columna 3
  titulo:                  Nombre
  tipo:                    t
  nombrecampo:             nom_cli
  html:                    [size="25" readonly=true ]
4:       # Columna 5
  titulo:                  Fecha Pago
  tipo:                    t
  nombrecampo:             fec_cob
  html:                    [size="8" readonly=true ]
5:       # Columna 6
  titulo:                  Monto Pagado
  tipo:                    m
  nombrecampo:             monto
  html:                    [size="6" readonly=true ]
  estotal:                 [true, totalp]
6:       # Columna 7
  titulo:                  Observacion
  tipo:                    t
  nombrecampo:             observa
  html:                    [size="25" readonly=true ]
  esgrabable:              true

