dev:
  profit:
    param:
      classname: DebugPDO
  sms:
    param:
      classname: DebugPDO
test:
  profit:
    param:
      classname: DebugPDO
  sms:
    param:
      classname: DebugPDO
all:
  profit:
    class: sfPropelDatabase
    param:
      phptype:   mssql
      classname: MssqlPropelPDO
      dsn:       dblib:host=192.168.1.104;dbname=RECADMAR
      username:  luelher
      password:  797965
      encoding:  
      pooling:   true
  sms:
    class: sfPropelDatabase
    param:
      dsn:      mysql:host=localhost;dbname=sms
      username: root
      password: root
      encoding:
      pooling:  true
