<?php


/**
 * This class adds structure of 'reng_tip' table to 'profit' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Tue Mar  9 02:09:53 2010
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.profit.map
 */
class RengTipMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.profit.map.RengTipMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(RengTipPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(RengTipPeer::TABLE_NAME);
		$tMap->setPhpName('RengTip');
		$tMap->setClassname('RengTip');

		$tMap->setUseIdGenerator(false);

		$tMap->addPrimaryKey('COB_NUM', 'CobNum', 'INTEGER', true, null);

		$tMap->addPrimaryKey('RENG_NUM', 'RengNum', 'INTEGER', true, null);

		$tMap->addColumn('TIP_COB', 'TipCob', 'CHAR', true, 4);

		$tMap->addColumn('MOVI', 'Movi', 'INTEGER', true, null);

		$tMap->addColumn('NUM_DOC', 'NumDoc', 'CHAR', true, 20);

		$tMap->addColumn('MONT_DOC', 'MontDoc', 'DECIMAL', true, 20);

		$tMap->addColumn('MONT_TMP', 'MontTmp', 'DECIMAL', true, 20);

		$tMap->addColumn('MONEDA', 'Moneda', 'CHAR', true, 8);

		$tMap->addColumn('BANCO', 'Banco', 'CHAR', true, 6);

		$tMap->addColumn('COD_CAJA', 'CodCaja', 'CHAR', true, 6);

		$tMap->addColumn('DES_CAJA', 'DesCaja', 'CHAR', true, 20);

		$tMap->addColumn('FEC_CHEQ', 'FecCheq', 'VARCHAR', true, 255);

		$tMap->addColumn('NOMBRE_BAN', 'NombreBan', 'CHAR', true, 15);

		$tMap->addColumn('NUMERO', 'Numero', 'CHAR', true, 20);

		$tMap->addColumn('DEVUELTO', 'Devuelto', 'BOOLEAN', true, null);

		$tMap->addColumn('ROWGUID', 'Rowguid', 'CHAR', true, 16);

		$tMap->addColumn('OPERADOR', 'Operador', 'CHAR', true, 4);

		$tMap->addColumn('CLAVE', 'Clave', 'CHAR', true, 6);

	} // doBuild()

} // RengTipMapBuilder
