<?php

/**
 * Art form base class.
 *
 * @package    sf_sandbox
 * @subpackage form
 * @author     Your name here
 * @version    SVN: $Id: sfPropelFormGeneratedTemplate.php 16976 2009-04-04 12:47:44Z fabien $
 */
class BaseArtForm extends BaseFormPropel
{
  public function setup()
  {
    $this->setWidgets(array(
      'co_art'     => new sfWidgetFormInputHidden(),
      'art_des'    => new sfWidgetFormInput(),
      'fecha_reg'  => new sfWidgetFormInput(),
      'manj_ser'   => new sfWidgetFormInputCheckbox(),
      'co_lin'     => new sfWidgetFormPropelChoice(array('model' => 'LinArt', 'add_empty' => false)),
      'co_cat'     => new sfWidgetFormPropelChoice(array('model' => 'CatArt', 'add_empty' => false)),
      'co_subl'    => new sfWidgetFormPropelChoice(array('model' => 'SubLin', 'add_empty' => false)),
      'co_color'   => new sfWidgetFormPropelChoice(array('model' => 'Colores', 'add_empty' => false)),
      'item'       => new sfWidgetFormInput(),
      'ref'        => new sfWidgetFormInput(),
      'modelo'     => new sfWidgetFormInput(),
      'procedenci' => new sfWidgetFormPropelChoice(array('model' => 'Proceden', 'add_empty' => false)),
      'comentario' => new sfWidgetFormTextarea(),
      'co_prov'    => new sfWidgetFormPropelChoice(array('model' => 'Prov', 'add_empty' => false)),
      'ubicacion'  => new sfWidgetFormInput(),
      'uni_venta'  => new sfWidgetFormPropelChoice(array('model' => 'Unidades', 'add_empty' => false)),
      'uni_compra' => new sfWidgetFormInput(),
      'uni_relac'  => new sfWidgetFormInput(),
      'relac_aut'  => new sfWidgetFormInput(),
      'stock_act'  => new sfWidgetFormInput(),
      'stock_com'  => new sfWidgetFormInput(),
      'sstock_com' => new sfWidgetFormInput(),
      'stock_lle'  => new sfWidgetFormInput(),
      'sstock_lle' => new sfWidgetFormInput(),
      'stock_des'  => new sfWidgetFormInput(),
      'sstock_des' => new sfWidgetFormInput(),
      'suni_venta' => new sfWidgetFormPropelChoice(array('model' => 'Unidades', 'add_empty' => false)),
      'suni_compr' => new sfWidgetFormInput(),
      'suni_relac' => new sfWidgetFormInput(),
      'sstock_act' => new sfWidgetFormInput(),
      'relac_comp' => new sfWidgetFormInput(),
      'relac_vent' => new sfWidgetFormInput(),
      'pto_pedido' => new sfWidgetFormInput(),
      'stock_max'  => new sfWidgetFormInput(),
      'stock_min'  => new sfWidgetFormInput(),
      'prec_om'    => new sfWidgetFormInputCheckbox(),
      'prec_vta1'  => new sfWidgetFormInput(),
      'fec_prec_v' => new sfWidgetFormInput(),
      'fec_prec_2' => new sfWidgetFormInput(),
      'prec_vta2'  => new sfWidgetFormInput(),
      'fec_prec_3' => new sfWidgetFormInput(),
      'prec_vta3'  => new sfWidgetFormInput(),
      'fec_prec_4' => new sfWidgetFormInput(),
      'prec_vta4'  => new sfWidgetFormInput(),
      'fec_prec_5' => new sfWidgetFormInput(),
      'prec_vta5'  => new sfWidgetFormInput(),
      'prec_agr1'  => new sfWidgetFormInput(),
      'prec_agr2'  => new sfWidgetFormInput(),
      'prec_agr3'  => new sfWidgetFormInput(),
      'prec_agr4'  => new sfWidgetFormInput(),
      'prec_agr5'  => new sfWidgetFormInput(),
      'can_agr'    => new sfWidgetFormInput(),
      'fec_des_p5' => new sfWidgetFormInput(),
      'fec_has_p5' => new sfWidgetFormInput(),
      'co_imp'     => new sfWidgetFormInput(),
      'margen_max' => new sfWidgetFormInput(),
      'ult_cos_un' => new sfWidgetFormInput(),
      'fec_ult_co' => new sfWidgetFormInput(),
      'cos_pro_un' => new sfWidgetFormInput(),
      'fec_cos_pr' => new sfWidgetFormInput(),
      'cos_merc'   => new sfWidgetFormInput(),
      'fec_cos_me' => new sfWidgetFormInput(),
      'cos_prov'   => new sfWidgetFormInput(),
      'fec_cos_p2' => new sfWidgetFormInput(),
      'ult_cos_do' => new sfWidgetFormInput(),
      'fec_cos_do' => new sfWidgetFormInput(),
      'cos_un_an'  => new sfWidgetFormInput(),
      'fec_cos_an' => new sfWidgetFormInput(),
      'ult_cos_om' => new sfWidgetFormInput(),
      'fec_ult_om' => new sfWidgetFormInput(),
      'cos_pro_om' => new sfWidgetFormInput(),
      'fec_pro_om' => new sfWidgetFormInput(),
      'tipo_cos'   => new sfWidgetFormInput(),
      'mont_comi'  => new sfWidgetFormInput(),
      'porc_cos'   => new sfWidgetFormInput(),
      'mont_cos'   => new sfWidgetFormInput(),
      'porc_gas'   => new sfWidgetFormInput(),
      'mont_gas'   => new sfWidgetFormInput(),
      'f_cost'     => new sfWidgetFormInput(),
      'fisico'     => new sfWidgetFormInputCheckbox(),
      'punt_cli'   => new sfWidgetFormInput(),
      'punt_pro'   => new sfWidgetFormInput(),
      'dias_repos' => new sfWidgetFormInput(),
      'tipo'       => new sfWidgetFormInput(),
      'alm_prin'   => new sfWidgetFormInput(),
      'anulado'    => new sfWidgetFormInputCheckbox(),
      'tipo_imp'   => new sfWidgetFormPropelChoice(array('model' => 'Tabulado', 'add_empty' => false)),
      'dis_cen'    => new sfWidgetFormTextarea(),
      'mon_ilc'    => new sfWidgetFormInput(),
      'capacidad'  => new sfWidgetFormInput(),
      'grado_al'   => new sfWidgetFormInput(),
      'tipo_licor' => new sfWidgetFormInput(),
      'compuesto'  => new sfWidgetFormInputCheckbox(),
      'picture'    => new sfWidgetFormInput(),
      'campo1'     => new sfWidgetFormInput(),
      'campo2'     => new sfWidgetFormInput(),
      'campo3'     => new sfWidgetFormInput(),
      'campo4'     => new sfWidgetFormInput(),
      'campo5'     => new sfWidgetFormInput(),
      'campo6'     => new sfWidgetFormInput(),
      'campo7'     => new sfWidgetFormInput(),
      'campo8'     => new sfWidgetFormInput(),
      'co_us_in'   => new sfWidgetFormInput(),
      'fe_us_in'   => new sfWidgetFormInput(),
      'co_us_mo'   => new sfWidgetFormInput(),
      'fe_us_mo'   => new sfWidgetFormInput(),
      'co_us_el'   => new sfWidgetFormInput(),
      'fe_us_el'   => new sfWidgetFormInput(),
      'revisado'   => new sfWidgetFormInput(),
      'trasnfe'    => new sfWidgetFormInput(),
      'co_sucu'    => new sfWidgetFormInput(),
      'rowguid'    => new sfWidgetFormInput(),
      'tuni_venta' => new sfWidgetFormInput(),
      'equi_uni1'  => new sfWidgetFormInput(),
      'equi_uni2'  => new sfWidgetFormInput(),
      'equi_uni3'  => new sfWidgetFormInput(),
      'lote'       => new sfWidgetFormInputCheckbox(),
      'serialp'    => new sfWidgetFormInput(),
      'valido'     => new sfWidgetFormInputCheckbox(),
      'atributo1'  => new sfWidgetFormInputCheckbox(),
      'vatributo1' => new sfWidgetFormInput(),
      'atributo2'  => new sfWidgetFormInputCheckbox(),
      'vatributo2' => new sfWidgetFormInput(),
      'atributo3'  => new sfWidgetFormInputCheckbox(),
      'vatributo3' => new sfWidgetFormInput(),
      'atributo4'  => new sfWidgetFormInputCheckbox(),
      'vatributo4' => new sfWidgetFormInput(),
      'atributo5'  => new sfWidgetFormInputCheckbox(),
      'vatributo5' => new sfWidgetFormInput(),
      'atributo6'  => new sfWidgetFormInputCheckbox(),
      'vatributo6' => new sfWidgetFormInput(),
      'garantia'   => new sfWidgetFormInput(),
      'peso'       => new sfWidgetFormInput(),
      'pie'        => new sfWidgetFormInput(),
      'margen1'    => new sfWidgetFormInput(),
      'margen2'    => new sfWidgetFormInput(),
      'margen3'    => new sfWidgetFormInput(),
      'margen4'    => new sfWidgetFormInput(),
      'margen5'    => new sfWidgetFormInput(),
      'row_id'     => new sfWidgetFormInput(),
      'imagen1'    => new sfWidgetFormInput(),
      'imagen2'    => new sfWidgetFormInput(),
      'i_art_des'  => new sfWidgetFormInput(),
      'uni_emp'    => new sfWidgetFormInput(),
      'rel_emp'    => new sfWidgetFormInput(),
      'movil'      => new sfWidgetFormInputCheckbox(),
    ));

    $this->setValidators(array(
      'co_art'     => new sfValidatorPropelChoice(array('model' => 'Art', 'column' => 'co_art', 'required' => false)),
      'art_des'    => new sfValidatorString(array('max_length' => 120)),
      'fecha_reg'  => new sfValidatorString(array('max_length' => 255)),
      'manj_ser'   => new sfValidatorBoolean(),
      'co_lin'     => new sfValidatorPropelChoice(array('model' => 'LinArt', 'column' => 'co_lin')),
      'co_cat'     => new sfValidatorPropelChoice(array('model' => 'CatArt', 'column' => 'co_cat')),
      'co_subl'    => new sfValidatorPropelChoice(array('model' => 'SubLin', 'column' => 'co_lin')),
      'co_color'   => new sfValidatorPropelChoice(array('model' => 'Colores', 'column' => 'co_col')),
      'item'       => new sfValidatorString(array('max_length' => 10)),
      'ref'        => new sfValidatorString(array('max_length' => 20)),
      'modelo'     => new sfValidatorString(array('max_length' => 20)),
      'procedenci' => new sfValidatorPropelChoice(array('model' => 'Proceden', 'column' => 'cod_proc')),
      'comentario' => new sfValidatorString(array('max_length' => 2147483647)),
      'co_prov'    => new sfValidatorPropelChoice(array('model' => 'Prov', 'column' => 'co_prov')),
      'ubicacion'  => new sfValidatorString(array('max_length' => 60)),
      'uni_venta'  => new sfValidatorPropelChoice(array('model' => 'Unidades', 'column' => 'co_uni')),
      'uni_compra' => new sfValidatorString(array('max_length' => 6)),
      'uni_relac'  => new sfValidatorNumber(),
      'relac_aut'  => new sfValidatorInteger(),
      'stock_act'  => new sfValidatorNumber(),
      'stock_com'  => new sfValidatorNumber(),
      'sstock_com' => new sfValidatorNumber(),
      'stock_lle'  => new sfValidatorNumber(),
      'sstock_lle' => new sfValidatorNumber(),
      'stock_des'  => new sfValidatorNumber(),
      'sstock_des' => new sfValidatorNumber(),
      'suni_venta' => new sfValidatorPropelChoice(array('model' => 'Unidades', 'column' => 'co_uni')),
      'suni_compr' => new sfValidatorString(array('max_length' => 6)),
      'suni_relac' => new sfValidatorNumber(),
      'sstock_act' => new sfValidatorNumber(),
      'relac_comp' => new sfValidatorNumber(),
      'relac_vent' => new sfValidatorNumber(),
      'pto_pedido' => new sfValidatorNumber(),
      'stock_max'  => new sfValidatorNumber(),
      'stock_min'  => new sfValidatorNumber(),
      'prec_om'    => new sfValidatorBoolean(),
      'prec_vta1'  => new sfValidatorNumber(),
      'fec_prec_v' => new sfValidatorString(array('max_length' => 255)),
      'fec_prec_2' => new sfValidatorString(array('max_length' => 255)),
      'prec_vta2'  => new sfValidatorNumber(),
      'fec_prec_3' => new sfValidatorString(array('max_length' => 255)),
      'prec_vta3'  => new sfValidatorNumber(),
      'fec_prec_4' => new sfValidatorString(array('max_length' => 255)),
      'prec_vta4'  => new sfValidatorNumber(),
      'fec_prec_5' => new sfValidatorString(array('max_length' => 255)),
      'prec_vta5'  => new sfValidatorNumber(),
      'prec_agr1'  => new sfValidatorNumber(),
      'prec_agr2'  => new sfValidatorNumber(),
      'prec_agr3'  => new sfValidatorNumber(),
      'prec_agr4'  => new sfValidatorNumber(),
      'prec_agr5'  => new sfValidatorNumber(),
      'can_agr'    => new sfValidatorNumber(),
      'fec_des_p5' => new sfValidatorString(array('max_length' => 255)),
      'fec_has_p5' => new sfValidatorString(array('max_length' => 255)),
      'co_imp'     => new sfValidatorString(array('max_length' => 4)),
      'margen_max' => new sfValidatorNumber(),
      'ult_cos_un' => new sfValidatorNumber(),
      'fec_ult_co' => new sfValidatorString(array('max_length' => 255)),
      'cos_pro_un' => new sfValidatorNumber(),
      'fec_cos_pr' => new sfValidatorString(array('max_length' => 255)),
      'cos_merc'   => new sfValidatorNumber(),
      'fec_cos_me' => new sfValidatorString(array('max_length' => 255)),
      'cos_prov'   => new sfValidatorNumber(),
      'fec_cos_p2' => new sfValidatorString(array('max_length' => 255)),
      'ult_cos_do' => new sfValidatorNumber(),
      'fec_cos_do' => new sfValidatorString(array('max_length' => 255)),
      'cos_un_an'  => new sfValidatorNumber(),
      'fec_cos_an' => new sfValidatorString(array('max_length' => 255)),
      'ult_cos_om' => new sfValidatorNumber(),
      'fec_ult_om' => new sfValidatorString(array('max_length' => 255)),
      'cos_pro_om' => new sfValidatorNumber(),
      'fec_pro_om' => new sfValidatorString(array('max_length' => 255)),
      'tipo_cos'   => new sfValidatorString(array('max_length' => 4)),
      'mont_comi'  => new sfValidatorNumber(),
      'porc_cos'   => new sfValidatorNumber(),
      'mont_cos'   => new sfValidatorNumber(),
      'porc_gas'   => new sfValidatorNumber(),
      'mont_gas'   => new sfValidatorNumber(),
      'f_cost'     => new sfValidatorString(array('max_length' => 255)),
      'fisico'     => new sfValidatorBoolean(),
      'punt_cli'   => new sfValidatorNumber(),
      'punt_pro'   => new sfValidatorNumber(),
      'dias_repos' => new sfValidatorInteger(),
      'tipo'       => new sfValidatorString(array('max_length' => 1)),
      'alm_prin'   => new sfValidatorString(array('max_length' => 4)),
      'anulado'    => new sfValidatorBoolean(),
      'tipo_imp'   => new sfValidatorPropelChoice(array('model' => 'Tabulado', 'column' => 'tipo')),
      'dis_cen'    => new sfValidatorString(array('max_length' => 2147483647)),
      'mon_ilc'    => new sfValidatorNumber(),
      'capacidad'  => new sfValidatorNumber(),
      'grado_al'   => new sfValidatorNumber(),
      'tipo_licor' => new sfValidatorString(array('max_length' => 1)),
      'compuesto'  => new sfValidatorBoolean(),
      'picture'    => new sfValidatorPass(array('required' => false)),
      'campo1'     => new sfValidatorString(array('max_length' => 60)),
      'campo2'     => new sfValidatorString(array('max_length' => 60)),
      'campo3'     => new sfValidatorString(array('max_length' => 60)),
      'campo4'     => new sfValidatorString(array('max_length' => 60)),
      'campo5'     => new sfValidatorString(array('max_length' => 60)),
      'campo6'     => new sfValidatorString(array('max_length' => 60)),
      'campo7'     => new sfValidatorString(array('max_length' => 60)),
      'campo8'     => new sfValidatorString(array('max_length' => 60)),
      'co_us_in'   => new sfValidatorString(array('max_length' => 4)),
      'fe_us_in'   => new sfValidatorString(array('max_length' => 255)),
      'co_us_mo'   => new sfValidatorString(array('max_length' => 4)),
      'fe_us_mo'   => new sfValidatorString(array('max_length' => 255)),
      'co_us_el'   => new sfValidatorString(array('max_length' => 4)),
      'fe_us_el'   => new sfValidatorString(array('max_length' => 255)),
      'revisado'   => new sfValidatorString(array('max_length' => 1)),
      'trasnfe'    => new sfValidatorString(array('max_length' => 1)),
      'co_sucu'    => new sfValidatorString(array('max_length' => 6)),
      'rowguid'    => new sfValidatorString(array('max_length' => 16)),
      'tuni_venta' => new sfValidatorString(array('max_length' => 6)),
      'equi_uni1'  => new sfValidatorNumber(),
      'equi_uni2'  => new sfValidatorNumber(),
      'equi_uni3'  => new sfValidatorNumber(),
      'lote'       => new sfValidatorBoolean(),
      'serialp'    => new sfValidatorString(array('max_length' => 30)),
      'valido'     => new sfValidatorBoolean(),
      'atributo1'  => new sfValidatorBoolean(),
      'vatributo1' => new sfValidatorString(array('max_length' => 15)),
      'atributo2'  => new sfValidatorBoolean(),
      'vatributo2' => new sfValidatorString(array('max_length' => 15)),
      'atributo3'  => new sfValidatorBoolean(),
      'vatributo3' => new sfValidatorString(array('max_length' => 15)),
      'atributo4'  => new sfValidatorBoolean(),
      'vatributo4' => new sfValidatorString(array('max_length' => 15)),
      'atributo5'  => new sfValidatorBoolean(),
      'vatributo5' => new sfValidatorString(array('max_length' => 15)),
      'atributo6'  => new sfValidatorBoolean(),
      'vatributo6' => new sfValidatorString(array('max_length' => 15)),
      'garantia'   => new sfValidatorString(array('max_length' => 30)),
      'peso'       => new sfValidatorNumber(),
      'pie'        => new sfValidatorNumber(),
      'margen1'    => new sfValidatorNumber(),
      'margen2'    => new sfValidatorNumber(),
      'margen3'    => new sfValidatorNumber(),
      'margen4'    => new sfValidatorNumber(),
      'margen5'    => new sfValidatorNumber(),
      'row_id'     => new sfValidatorPass(),
      'imagen1'    => new sfValidatorString(array('max_length' => 60)),
      'imagen2'    => new sfValidatorString(array('max_length' => 60)),
      'i_art_des'  => new sfValidatorString(array('max_length' => 60)),
      'uni_emp'    => new sfValidatorString(array('max_length' => 6)),
      'rel_emp'    => new sfValidatorNumber(),
      'movil'      => new sfValidatorBoolean(),
    ));

    $this->widgetSchema->setNameFormat('art[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    parent::setup();
  }

  public function getModelName()
  {
    return 'Art';
  }


}
