<?php

/**
 * Clientes form base class.
 *
 * @package    sf_sandbox
 * @subpackage form
 * @author     Your name here
 * @version    SVN: $Id: sfPropelFormGeneratedTemplate.php 16976 2009-04-04 12:47:44Z fabien $
 */
class BaseClientesForm extends BaseFormPropel
{
  public function setup()
  {
    $this->setWidgets(array(
      'co_cli'     => new sfWidgetFormInputHidden(),
      'tipo'       => new sfWidgetFormPropelChoice(array('model' => 'TipoCli', 'add_empty' => false)),
      'cli_des'    => new sfWidgetFormInput(),
      'direc1'     => new sfWidgetFormTextarea(),
      'direc2'     => new sfWidgetFormInput(),
      'telefonos'  => new sfWidgetFormInput(),
      'fax'        => new sfWidgetFormInput(),
      'inactivo'   => new sfWidgetFormInputCheckbox(),
      'comentario' => new sfWidgetFormTextarea(),
      'respons'    => new sfWidgetFormInput(),
      'fecha_reg'  => new sfWidgetFormInput(),
      'puntaje'    => new sfWidgetFormInput(),
      'saldo'      => new sfWidgetFormInput(),
      'saldo_ini'  => new sfWidgetFormInput(),
      'fac_ult_ve' => new sfWidgetFormInput(),
      'fec_ult_ve' => new sfWidgetFormInput(),
      'net_ult_ve' => new sfWidgetFormInput(),
      'mont_cre'   => new sfWidgetFormInput(),
      'plaz_pag'   => new sfWidgetFormInput(),
      'desc_ppago' => new sfWidgetFormInput(),
      'co_zon'     => new sfWidgetFormPropelChoice(array('model' => 'Zona', 'add_empty' => false)),
      'co_seg'     => new sfWidgetFormPropelChoice(array('model' => 'Segmento', 'add_empty' => false)),
      'co_ven'     => new sfWidgetFormPropelChoice(array('model' => 'Vendedor', 'add_empty' => false)),
      'desc_glob'  => new sfWidgetFormInput(),
      'horar_caja' => new sfWidgetFormInput(),
      'frecu_vist' => new sfWidgetFormInput(),
      'lunes'      => new sfWidgetFormInputCheckbox(),
      'martes'     => new sfWidgetFormInputCheckbox(),
      'miercoles'  => new sfWidgetFormInputCheckbox(),
      'jueves'     => new sfWidgetFormInputCheckbox(),
      'viernes'    => new sfWidgetFormInputCheckbox(),
      'sabado'     => new sfWidgetFormInputCheckbox(),
      'domingo'    => new sfWidgetFormInputCheckbox(),
      'dir_ent2'   => new sfWidgetFormTextarea(),
      'tipo_iva'   => new sfWidgetFormInput(),
      'iva'        => new sfWidgetFormInput(),
      'rif'        => new sfWidgetFormInput(),
      'contribu'   => new sfWidgetFormInputCheckbox(),
      'dis_cen'    => new sfWidgetFormTextarea(),
      'nit'        => new sfWidgetFormInput(),
      'email'      => new sfWidgetFormInput(),
      'co_ingr'    => new sfWidgetFormPropelChoice(array('model' => 'CtaIngr', 'add_empty' => false)),
      'campo1'     => new sfWidgetFormInput(),
      'campo2'     => new sfWidgetFormInput(),
      'campo3'     => new sfWidgetFormInput(),
      'campo4'     => new sfWidgetFormInput(),
      'campo5'     => new sfWidgetFormInput(),
      'campo6'     => new sfWidgetFormInput(),
      'campo7'     => new sfWidgetFormInput(),
      'campo8'     => new sfWidgetFormInput(),
      'co_us_in'   => new sfWidgetFormInput(),
      'fe_us_in'   => new sfWidgetFormInput(),
      'co_us_mo'   => new sfWidgetFormInput(),
      'fe_us_mo'   => new sfWidgetFormInput(),
      'co_us_el'   => new sfWidgetFormInput(),
      'fe_us_el'   => new sfWidgetFormInput(),
      'revisado'   => new sfWidgetFormInput(),
      'trasnfe'    => new sfWidgetFormInput(),
      'co_sucu'    => new sfWidgetFormInput(),
      'rowguid'    => new sfWidgetFormInput(),
      'juridico'   => new sfWidgetFormInputCheckbox(),
      'tipo_adi'   => new sfWidgetFormInput(),
      'matriz'     => new sfWidgetFormInput(),
      'co_tab'     => new sfWidgetFormInput(),
      'tipo_per'   => new sfWidgetFormInput(),
      'serialp'    => new sfWidgetFormInput(),
      'valido'     => new sfWidgetFormInputCheckbox(),
      'row_id'     => new sfWidgetFormInput(),
      'estado'     => new sfWidgetFormInput(),
      'Id'         => new sfWidgetFormInput(),
      'co_pais'    => new sfWidgetFormInput(),
      'ciudad'     => new sfWidgetFormInput(),
      'zip'        => new sfWidgetFormInput(),
      'login'      => new sfWidgetFormInput(),
      'password'   => new sfWidgetFormInput(),
      'website'    => new sfWidgetFormInput(),
      'salestax'   => new sfWidgetFormInput(),
      'contribu_e' => new sfWidgetFormInputCheckbox(),
      'porc_esp'   => new sfWidgetFormInput(),
    ));

    $this->setValidators(array(
      'co_cli'     => new sfValidatorPropelChoice(array('model' => 'Clientes', 'column' => 'co_cli', 'required' => false)),
      'tipo'       => new sfValidatorPropelChoice(array('model' => 'TipoCli', 'column' => 'tip_cli')),
      'cli_des'    => new sfValidatorString(array('max_length' => 60)),
      'direc1'     => new sfValidatorString(array('max_length' => 2147483647)),
      'direc2'     => new sfValidatorString(array('max_length' => 60)),
      'telefonos'  => new sfValidatorString(array('max_length' => 60)),
      'fax'        => new sfValidatorString(array('max_length' => 60)),
      'inactivo'   => new sfValidatorBoolean(),
      'comentario' => new sfValidatorString(array('max_length' => 2147483647)),
      'respons'    => new sfValidatorString(array('max_length' => 60)),
      'fecha_reg'  => new sfValidatorString(array('max_length' => 255)),
      'puntaje'    => new sfValidatorInteger(),
      'saldo'      => new sfValidatorNumber(),
      'saldo_ini'  => new sfValidatorNumber(),
      'fac_ult_ve' => new sfValidatorInteger(),
      'fec_ult_ve' => new sfValidatorString(array('max_length' => 255)),
      'net_ult_ve' => new sfValidatorNumber(),
      'mont_cre'   => new sfValidatorNumber(),
      'plaz_pag'   => new sfValidatorInteger(),
      'desc_ppago' => new sfValidatorNumber(),
      'co_zon'     => new sfValidatorPropelChoice(array('model' => 'Zona', 'column' => 'co_zon')),
      'co_seg'     => new sfValidatorPropelChoice(array('model' => 'Segmento', 'column' => 'co_seg')),
      'co_ven'     => new sfValidatorPropelChoice(array('model' => 'Vendedor', 'column' => 'co_ven')),
      'desc_glob'  => new sfValidatorNumber(),
      'horar_caja' => new sfValidatorString(array('max_length' => 60)),
      'frecu_vist' => new sfValidatorString(array('max_length' => 60)),
      'lunes'      => new sfValidatorBoolean(),
      'martes'     => new sfValidatorBoolean(),
      'miercoles'  => new sfValidatorBoolean(),
      'jueves'     => new sfValidatorBoolean(),
      'viernes'    => new sfValidatorBoolean(),
      'sabado'     => new sfValidatorBoolean(),
      'domingo'    => new sfValidatorBoolean(),
      'dir_ent2'   => new sfValidatorString(array('max_length' => 2147483647)),
      'tipo_iva'   => new sfValidatorString(array('max_length' => 1)),
      'iva'        => new sfValidatorNumber(),
      'rif'        => new sfValidatorString(array('max_length' => 18)),
      'contribu'   => new sfValidatorBoolean(),
      'dis_cen'    => new sfValidatorString(array('max_length' => 2147483647)),
      'nit'        => new sfValidatorString(array('max_length' => 18)),
      'email'      => new sfValidatorString(array('max_length' => 60)),
      'co_ingr'    => new sfValidatorPropelChoice(array('model' => 'CtaIngr', 'column' => 'co_ingr')),
      'campo1'     => new sfValidatorString(array('max_length' => 60)),
      'campo2'     => new sfValidatorString(array('max_length' => 60)),
      'campo3'     => new sfValidatorString(array('max_length' => 60)),
      'campo4'     => new sfValidatorString(array('max_length' => 60)),
      'campo5'     => new sfValidatorString(array('max_length' => 60)),
      'campo6'     => new sfValidatorString(array('max_length' => 60)),
      'campo7'     => new sfValidatorString(array('max_length' => 60)),
      'campo8'     => new sfValidatorString(array('max_length' => 60)),
      'co_us_in'   => new sfValidatorString(array('max_length' => 4)),
      'fe_us_in'   => new sfValidatorString(array('max_length' => 255)),
      'co_us_mo'   => new sfValidatorString(array('max_length' => 4)),
      'fe_us_mo'   => new sfValidatorString(array('max_length' => 255)),
      'co_us_el'   => new sfValidatorString(array('max_length' => 4)),
      'fe_us_el'   => new sfValidatorString(array('max_length' => 255)),
      'revisado'   => new sfValidatorString(array('max_length' => 1)),
      'trasnfe'    => new sfValidatorString(array('max_length' => 1)),
      'co_sucu'    => new sfValidatorString(array('max_length' => 6)),
      'rowguid'    => new sfValidatorString(array('max_length' => 16)),
      'juridico'   => new sfValidatorBoolean(),
      'tipo_adi'   => new sfValidatorNumber(),
      'matriz'     => new sfValidatorString(array('max_length' => 10)),
      'co_tab'     => new sfValidatorInteger(),
      'tipo_per'   => new sfValidatorString(array('max_length' => 1)),
      'serialp'    => new sfValidatorString(array('max_length' => 30)),
      'valido'     => new sfValidatorBoolean(),
      'row_id'     => new sfValidatorPass(),
      'estado'     => new sfValidatorString(array('max_length' => 1)),
      'Id'         => new sfValidatorInteger(),
      'co_pais'    => new sfValidatorString(array('max_length' => 6)),
      'ciudad'     => new sfValidatorString(array('max_length' => 50)),
      'zip'        => new sfValidatorString(array('max_length' => 10)),
      'login'      => new sfValidatorString(array('max_length' => 10)),
      'password'   => new sfValidatorString(array('max_length' => 50)),
      'website'    => new sfValidatorString(array('max_length' => 200)),
      'salestax'   => new sfValidatorString(array('max_length' => 8)),
      'contribu_e' => new sfValidatorBoolean(),
      'porc_esp'   => new sfValidatorNumber(),
    ));

    $this->widgetSchema->setNameFormat('clientes[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    parent::setup();
  }

  public function getModelName()
  {
    return 'Clientes';
  }


}
