<?php

/**
 * Almacen form base class.
 *
 * @package    sf_sandbox
 * @subpackage form
 * @author     Your name here
 * @version    SVN: $Id: sfPropelFormGeneratedTemplate.php 16976 2009-04-04 12:47:44Z fabien $
 */
class BaseAlmacenForm extends BaseFormPropel
{
  public function setup()
  {
    $this->setWidgets(array(
      'co_alma'     => new sfWidgetFormInputHidden(),
      'alma_des'    => new sfWidgetFormInput(),
      'nro_fact'    => new sfWidgetFormInput(),
      'num_fac_ini' => new sfWidgetFormInput(),
      'num_fac_fin' => new sfWidgetFormInput(),
      'campo1'      => new sfWidgetFormInput(),
      'campo2'      => new sfWidgetFormInput(),
      'campo3'      => new sfWidgetFormInput(),
      'campo4'      => new sfWidgetFormInput(),
      'co_us_in'    => new sfWidgetFormInput(),
      'fe_us_in'    => new sfWidgetFormInput(),
      'co_us_mo'    => new sfWidgetFormInput(),
      'fe_us_mo'    => new sfWidgetFormInput(),
      'co_us_el'    => new sfWidgetFormInput(),
      'fe_us_el'    => new sfWidgetFormInput(),
      'revisado'    => new sfWidgetFormInput(),
      'trasnfe'     => new sfWidgetFormInput(),
      'co_sucu'     => new sfWidgetFormInput(),
      'rowguid'     => new sfWidgetFormInput(),
      'nc_num'      => new sfWidgetFormInput(),
      'nd_num'      => new sfWidgetFormInput(),
      'ajus_num'    => new sfWidgetFormInput(),
      'tras_num'    => new sfWidgetFormInput(),
      'fisi_num'    => new sfWidgetFormInput(),
      'num_kit'     => new sfWidgetFormInput(),
      'genk_num'    => new sfWidgetFormInput(),
      'fact_num'    => new sfWidgetFormInput(),
      'ped_num'     => new sfWidgetFormInput(),
      'cotc_num'    => new sfWidgetFormInput(),
      'devc_num'    => new sfWidgetFormInput(),
      'nde_num'     => new sfWidgetFormInput(),
      'ndd_num'     => new sfWidgetFormInput(),
      'post_num'    => new sfWidgetFormInput(),
      'cfxg_num'    => new sfWidgetFormInput(),
      'chdv_num'    => new sfWidgetFormInput(),
      'giro_num'    => new sfWidgetFormInput(),
      'reten_num'   => new sfWidgetFormInput(),
      'cb_num'      => new sfWidgetFormInput(),
      'movb_num'    => new sfWidgetFormInput(),
      'movc_num'    => new sfWidgetFormInput(),
      'ordp_num'    => new sfWidgetFormInput(),
      'depc_num'    => new sfWidgetFormInput(),
      'comp_num'    => new sfWidgetFormInput(),
      'ord_num'     => new sfWidgetFormInput(),
      'cotp_num'    => new sfWidgetFormInput(),
      'devp_num'    => new sfWidgetFormInput(),
      'ndr_num'     => new sfWidgetFormInput(),
      'postcppnum'  => new sfWidgetFormInput(),
      'ccxg_num'    => new sfWidgetFormInput(),
      'chdvcppnum'  => new sfWidgetFormInput(),
      'girocppnum'  => new sfWidgetFormInput(),
      'nccpp_num'   => new sfWidgetFormInput(),
      'ndcpp_num'   => new sfWidgetFormInput(),
      'retencppnum' => new sfWidgetFormInput(),
      'pg_num'      => new sfWidgetFormInput(),
      'aju_posm'    => new sfWidgetFormInput(),
      'aju_posa'    => new sfWidgetFormInput(),
      'aju_negm'    => new sfWidgetFormInput(),
      'aju_nega'    => new sfWidgetFormInput(),
      'aju_posmc'   => new sfWidgetFormInput(),
      'aju_posac'   => new sfWidgetFormInput(),
      'aju_negmc'   => new sfWidgetFormInput(),
      'aju_negac'   => new sfWidgetFormInput(),
      'pventa'      => new sfWidgetFormInput(),
      'turnosic'    => new sfWidgetFormInput(),
      'plv_num'     => new sfWidgetFormInput(),
      'plc_num'     => new sfWidgetFormInput(),
      'tabislr'     => new sfWidgetFormInput(),
      'imp_num'     => new sfWidgetFormInput(),
      'rma_cli'     => new sfWidgetFormInput(),
      'rma_prov'    => new sfWidgetFormInput(),
      'rma_entc'    => new sfWidgetFormInput(),
      'rma_entp'    => new sfWidgetFormInput(),
      'rma_regs'    => new sfWidgetFormInput(),
      'fact_s1'     => new sfWidgetFormInput(),
      'fact_s2'     => new sfWidgetFormInput(),
      'fact_s3'     => new sfWidgetFormInput(),
      'fact_s4'     => new sfWidgetFormInput(),
      'fact_s5'     => new sfWidgetFormInput(),
      'nde_s1'      => new sfWidgetFormInput(),
      'nde_s2'      => new sfWidgetFormInput(),
      'nde_s3'      => new sfWidgetFormInput(),
      'nde_s4'      => new sfWidgetFormInput(),
      'nde_s5'      => new sfWidgetFormInput(),
      'nc_s1'       => new sfWidgetFormInput(),
      'nc_s2'       => new sfWidgetFormInput(),
      'nc_s3'       => new sfWidgetFormInput(),
      'nc_s4'       => new sfWidgetFormInput(),
      'nc_s5'       => new sfWidgetFormInput(),
      'nd_s1'       => new sfWidgetFormInput(),
      'nd_s2'       => new sfWidgetFormInput(),
      'nd_s3'       => new sfWidgetFormInput(),
      'nd_s4'       => new sfWidgetFormInput(),
      'nd_s5'       => new sfWidgetFormInput(),
      'fact_f1'     => new sfWidgetFormInput(),
      'fact_f2'     => new sfWidgetFormInput(),
      'fact_f3'     => new sfWidgetFormInput(),
      'fact_f4'     => new sfWidgetFormInput(),
      'nde_f1'      => new sfWidgetFormInput(),
      'nde_f2'      => new sfWidgetFormInput(),
      'nde_f3'      => new sfWidgetFormInput(),
      'nde_f4'      => new sfWidgetFormInput(),
      'nc_f1'       => new sfWidgetFormInput(),
      'nc_f2'       => new sfWidgetFormInput(),
      'nc_f3'       => new sfWidgetFormInput(),
      'nc_f4'       => new sfWidgetFormInput(),
      'nd_f1'       => new sfWidgetFormInput(),
      'nd_f2'       => new sfWidgetFormInput(),
      'nd_f3'       => new sfWidgetFormInput(),
      'nd_f4'       => new sfWidgetFormInput(),
      'fact_p1'     => new sfWidgetFormInput(),
      'fact_p2'     => new sfWidgetFormInput(),
      'fact_p3'     => new sfWidgetFormInput(),
      'fact_p4'     => new sfWidgetFormInput(),
      'fact_p5'     => new sfWidgetFormInput(),
      'nde_p1'      => new sfWidgetFormInput(),
      'nde_p2'      => new sfWidgetFormInput(),
      'nde_p3'      => new sfWidgetFormInput(),
      'nde_p4'      => new sfWidgetFormInput(),
      'nde_p5'      => new sfWidgetFormInput(),
      'nc_p1'       => new sfWidgetFormInput(),
      'nc_p2'       => new sfWidgetFormInput(),
      'nc_p3'       => new sfWidgetFormInput(),
      'nc_p4'       => new sfWidgetFormInput(),
      'nc_p5'       => new sfWidgetFormInput(),
      'nd_p1'       => new sfWidgetFormInput(),
      'nd_p2'       => new sfWidgetFormInput(),
      'nd_p3'       => new sfWidgetFormInput(),
      'nd_p4'       => new sfWidgetFormInput(),
      'nd_p5'       => new sfWidgetFormInput(),
      'fact_num2'   => new sfWidgetFormInput(),
      'fact_num3'   => new sfWidgetFormInput(),
      'fact_num4'   => new sfWidgetFormInput(),
      'fact_num5'   => new sfWidgetFormInput(),
      'nde_num2'    => new sfWidgetFormInput(),
      'nde_num3'    => new sfWidgetFormInput(),
      'nde_num4'    => new sfWidgetFormInput(),
      'nde_num5'    => new sfWidgetFormInput(),
      'nc_num2'     => new sfWidgetFormInput(),
      'nc_num3'     => new sfWidgetFormInput(),
      'nc_num4'     => new sfWidgetFormInput(),
      'nc_num5'     => new sfWidgetFormInput(),
      'nd_num2'     => new sfWidgetFormInput(),
      'nd_num3'     => new sfWidgetFormInput(),
      'nd_num4'     => new sfWidgetFormInput(),
      'nd_num5'     => new sfWidgetFormInput(),
      'serie2'      => new sfWidgetFormInputCheckbox(),
      'serie3'      => new sfWidgetFormInputCheckbox(),
      'serie4'      => new sfWidgetFormInputCheckbox(),
      'serie5'      => new sfWidgetFormInputCheckbox(),
      'emp_num'     => new sfWidgetFormInput(),
      'dmc_num'     => new sfWidgetFormInput(),
      'tax_num'     => new sfWidgetFormInput(),
      'ced_num'     => new sfWidgetFormInput(),
      'ent_num'     => new sfWidgetFormInput(),
      'cie_num'     => new sfWidgetFormInput(),
      'odp_num'     => new sfWidgetFormInput(),
      'req_num'     => new sfWidgetFormInput(),
      'dev_num'     => new sfWidgetFormInput(),
      'exp_num'     => new sfWidgetFormInput(),
      'inp_num'     => new sfWidgetFormInput(),
      'cost_num'    => new sfWidgetFormInput(),
      'par_num'     => new sfWidgetFormInput(),
      'esc_num'     => new sfWidgetFormInput(),
      'pla_num'     => new sfWidgetFormInput(),
      'men_num'     => new sfWidgetFormInput(),
      'dist_num'    => new sfWidgetFormInput(),
      'exp_numi'    => new sfWidgetFormInput(),
    ));

    $this->setValidators(array(
      'co_alma'     => new sfValidatorPropelChoice(array('model' => 'Almacen', 'column' => 'co_alma', 'required' => false)),
      'alma_des'    => new sfValidatorString(array('max_length' => 60)),
      'nro_fact'    => new sfValidatorInteger(),
      'num_fac_ini' => new sfValidatorInteger(),
      'num_fac_fin' => new sfValidatorInteger(),
      'campo1'      => new sfValidatorString(array('max_length' => 60)),
      'campo2'      => new sfValidatorString(array('max_length' => 60)),
      'campo3'      => new sfValidatorString(array('max_length' => 60)),
      'campo4'      => new sfValidatorString(array('max_length' => 60)),
      'co_us_in'    => new sfValidatorString(array('max_length' => 4)),
      'fe_us_in'    => new sfValidatorString(array('max_length' => 255)),
      'co_us_mo'    => new sfValidatorString(array('max_length' => 4)),
      'fe_us_mo'    => new sfValidatorString(array('max_length' => 255)),
      'co_us_el'    => new sfValidatorString(array('max_length' => 4)),
      'fe_us_el'    => new sfValidatorString(array('max_length' => 255)),
      'revisado'    => new sfValidatorString(array('max_length' => 1)),
      'trasnfe'     => new sfValidatorString(array('max_length' => 1)),
      'co_sucu'     => new sfValidatorString(array('max_length' => 6)),
      'rowguid'     => new sfValidatorString(array('max_length' => 16)),
      'nc_num'      => new sfValidatorInteger(),
      'nd_num'      => new sfValidatorInteger(),
      'ajus_num'    => new sfValidatorInteger(),
      'tras_num'    => new sfValidatorInteger(),
      'fisi_num'    => new sfValidatorInteger(),
      'num_kit'     => new sfValidatorInteger(),
      'genk_num'    => new sfValidatorInteger(),
      'fact_num'    => new sfValidatorInteger(),
      'ped_num'     => new sfValidatorInteger(),
      'cotc_num'    => new sfValidatorInteger(),
      'devc_num'    => new sfValidatorInteger(),
      'nde_num'     => new sfValidatorInteger(),
      'ndd_num'     => new sfValidatorInteger(),
      'post_num'    => new sfValidatorInteger(),
      'cfxg_num'    => new sfValidatorInteger(),
      'chdv_num'    => new sfValidatorInteger(),
      'giro_num'    => new sfValidatorInteger(),
      'reten_num'   => new sfValidatorInteger(),
      'cb_num'      => new sfValidatorInteger(),
      'movb_num'    => new sfValidatorInteger(),
      'movc_num'    => new sfValidatorInteger(),
      'ordp_num'    => new sfValidatorInteger(),
      'depc_num'    => new sfValidatorInteger(),
      'comp_num'    => new sfValidatorInteger(),
      'ord_num'     => new sfValidatorInteger(),
      'cotp_num'    => new sfValidatorInteger(),
      'devp_num'    => new sfValidatorInteger(),
      'ndr_num'     => new sfValidatorInteger(),
      'postcppnum'  => new sfValidatorInteger(),
      'ccxg_num'    => new sfValidatorInteger(),
      'chdvcppnum'  => new sfValidatorInteger(),
      'girocppnum'  => new sfValidatorInteger(),
      'nccpp_num'   => new sfValidatorInteger(),
      'ndcpp_num'   => new sfValidatorInteger(),
      'retencppnum' => new sfValidatorInteger(),
      'pg_num'      => new sfValidatorInteger(),
      'aju_posm'    => new sfValidatorInteger(),
      'aju_posa'    => new sfValidatorInteger(),
      'aju_negm'    => new sfValidatorInteger(),
      'aju_nega'    => new sfValidatorInteger(),
      'aju_posmc'   => new sfValidatorInteger(),
      'aju_posac'   => new sfValidatorInteger(),
      'aju_negmc'   => new sfValidatorInteger(),
      'aju_negac'   => new sfValidatorInteger(),
      'pventa'      => new sfValidatorInteger(),
      'turnosic'    => new sfValidatorInteger(),
      'plv_num'     => new sfValidatorInteger(),
      'plc_num'     => new sfValidatorInteger(),
      'tabislr'     => new sfValidatorInteger(),
      'imp_num'     => new sfValidatorInteger(),
      'rma_cli'     => new sfValidatorInteger(),
      'rma_prov'    => new sfValidatorInteger(),
      'rma_entc'    => new sfValidatorInteger(),
      'rma_entp'    => new sfValidatorInteger(),
      'rma_regs'    => new sfValidatorInteger(),
      'fact_s1'     => new sfValidatorString(array('max_length' => 10)),
      'fact_s2'     => new sfValidatorString(array('max_length' => 10)),
      'fact_s3'     => new sfValidatorString(array('max_length' => 10)),
      'fact_s4'     => new sfValidatorString(array('max_length' => 10)),
      'fact_s5'     => new sfValidatorString(array('max_length' => 10)),
      'nde_s1'      => new sfValidatorString(array('max_length' => 10)),
      'nde_s2'      => new sfValidatorString(array('max_length' => 10)),
      'nde_s3'      => new sfValidatorString(array('max_length' => 10)),
      'nde_s4'      => new sfValidatorString(array('max_length' => 10)),
      'nde_s5'      => new sfValidatorString(array('max_length' => 10)),
      'nc_s1'       => new sfValidatorString(array('max_length' => 10)),
      'nc_s2'       => new sfValidatorString(array('max_length' => 10)),
      'nc_s3'       => new sfValidatorString(array('max_length' => 10)),
      'nc_s4'       => new sfValidatorString(array('max_length' => 10)),
      'nc_s5'       => new sfValidatorString(array('max_length' => 10)),
      'nd_s1'       => new sfValidatorString(array('max_length' => 10)),
      'nd_s2'       => new sfValidatorString(array('max_length' => 10)),
      'nd_s3'       => new sfValidatorString(array('max_length' => 10)),
      'nd_s4'       => new sfValidatorString(array('max_length' => 10)),
      'nd_s5'       => new sfValidatorString(array('max_length' => 10)),
      'fact_f1'     => new sfValidatorInteger(),
      'fact_f2'     => new sfValidatorInteger(),
      'fact_f3'     => new sfValidatorInteger(),
      'fact_f4'     => new sfValidatorInteger(),
      'nde_f1'      => new sfValidatorInteger(),
      'nde_f2'      => new sfValidatorInteger(),
      'nde_f3'      => new sfValidatorInteger(),
      'nde_f4'      => new sfValidatorInteger(),
      'nc_f1'       => new sfValidatorInteger(),
      'nc_f2'       => new sfValidatorInteger(),
      'nc_f3'       => new sfValidatorInteger(),
      'nc_f4'       => new sfValidatorInteger(),
      'nd_f1'       => new sfValidatorInteger(),
      'nd_f2'       => new sfValidatorInteger(),
      'nd_f3'       => new sfValidatorInteger(),
      'nd_f4'       => new sfValidatorInteger(),
      'fact_p1'     => new sfValidatorInteger(),
      'fact_p2'     => new sfValidatorInteger(),
      'fact_p3'     => new sfValidatorInteger(),
      'fact_p4'     => new sfValidatorInteger(),
      'fact_p5'     => new sfValidatorInteger(),
      'nde_p1'      => new sfValidatorInteger(),
      'nde_p2'      => new sfValidatorInteger(),
      'nde_p3'      => new sfValidatorInteger(),
      'nde_p4'      => new sfValidatorInteger(),
      'nde_p5'      => new sfValidatorInteger(),
      'nc_p1'       => new sfValidatorInteger(),
      'nc_p2'       => new sfValidatorInteger(),
      'nc_p3'       => new sfValidatorInteger(),
      'nc_p4'       => new sfValidatorInteger(),
      'nc_p5'       => new sfValidatorInteger(),
      'nd_p1'       => new sfValidatorInteger(),
      'nd_p2'       => new sfValidatorInteger(),
      'nd_p3'       => new sfValidatorInteger(),
      'nd_p4'       => new sfValidatorInteger(),
      'nd_p5'       => new sfValidatorInteger(),
      'fact_num2'   => new sfValidatorInteger(),
      'fact_num3'   => new sfValidatorInteger(),
      'fact_num4'   => new sfValidatorInteger(),
      'fact_num5'   => new sfValidatorInteger(),
      'nde_num2'    => new sfValidatorInteger(),
      'nde_num3'    => new sfValidatorInteger(),
      'nde_num4'    => new sfValidatorInteger(),
      'nde_num5'    => new sfValidatorInteger(),
      'nc_num2'     => new sfValidatorInteger(),
      'nc_num3'     => new sfValidatorInteger(),
      'nc_num4'     => new sfValidatorInteger(),
      'nc_num5'     => new sfValidatorInteger(),
      'nd_num2'     => new sfValidatorInteger(),
      'nd_num3'     => new sfValidatorInteger(),
      'nd_num4'     => new sfValidatorInteger(),
      'nd_num5'     => new sfValidatorInteger(),
      'serie2'      => new sfValidatorBoolean(),
      'serie3'      => new sfValidatorBoolean(),
      'serie4'      => new sfValidatorBoolean(),
      'serie5'      => new sfValidatorBoolean(),
      'emp_num'     => new sfValidatorInteger(),
      'dmc_num'     => new sfValidatorInteger(),
      'tax_num'     => new sfValidatorInteger(),
      'ced_num'     => new sfValidatorInteger(),
      'ent_num'     => new sfValidatorInteger(),
      'cie_num'     => new sfValidatorInteger(),
      'odp_num'     => new sfValidatorInteger(),
      'req_num'     => new sfValidatorInteger(),
      'dev_num'     => new sfValidatorInteger(),
      'exp_num'     => new sfValidatorInteger(),
      'inp_num'     => new sfValidatorInteger(),
      'cost_num'    => new sfValidatorInteger(),
      'par_num'     => new sfValidatorInteger(),
      'esc_num'     => new sfValidatorInteger(),
      'pla_num'     => new sfValidatorInteger(),
      'men_num'     => new sfValidatorInteger(),
      'dist_num'    => new sfValidatorInteger(),
      'exp_numi'    => new sfValidatorInteger(),
    ));

    $this->widgetSchema->setNameFormat('almacen[%s]');

    $this->errorSchema = new sfValidatorErrorSchema($this->validatorSchema);

    parent::setup();
  }

  public function getModelName()
  {
    return 'Almacen';
  }


}
